### PR TITLE
Fix macOS nix CI

### LINKED ISSUE #2104: macOS Nix builld is broken
## Description

macos Nix build is broken.  Fix is detailed here: https://github.com/cachix/install-nix-action/issues/183#issuecomment-1596385740

### PR DESCRIPTION
**Pull request by ribose-jeffreylau**
closes #2104

### CODE REVIEW

**Comment by ni4** [comment]
@ribose-jeffreylau Should not this be a single commit to main branch instead of 10 to the [rnpgp:antonsviridenko-1980-ripemd160-def-prov-openssl3](https://github.com/rnpgp/rnp/tree/antonsviridenko-1980-ripemd160-def-prov-openssl3) ?

**Comment by ribose-jeffreylau** [comment]
> @ribose-jeffreylau Should not this be a single commit to main branch instead of 10 to the [rnpgp:antonsviridenko-1980-ripemd160-def-prov-openssl3](https://github.com/rnpgp/rnp/tree/antonsviridenko-1980-ripemd160-def-prov-openssl3) ?

Ah, retargeted to main branch now.  Thanks!

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Comment by ni4** [comment]
Merging with 1 approval as CI-only.

**Pull request merged**
