### PR TITLE
Avoid embedding major version number in library name

### PR DESCRIPTION
**Pull request by dewyatt**
Continued from https://github.com/rnpgp/rnp/pull/1417

### CODE REVIEW

**Comment by dewyatt** [comment]
We'll need to update oss-fuzz too

**Comment by dewyatt** [comment]
Do we want to merge this and make a release or address the oss-fuzz issue first?

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@dewyatt let's merge this first. Updating CIFuzz can be a separate, parallel process. Thanks

**Comment by dewyatt** [comment]
> LGTM, thanks!
> I can make PR to oss-fuzz, or do you want to do that?

You can please

**Comment by ni4** [comment]
Done: https://github.com/google/oss-fuzz/pull/5327

**Pull request merged**
