### PR TITLE
Disable SC2295.

### PR DESCRIPTION
**Pull request by ni4**
As title says.

### CODE REVIEW

**Comment by maxirmx** [comment]
It is already there: https://github.com/rnpgp/rnp/pull/1666

**Comment by ronaldtse** [comment]
Not sure why this is failing:

```
2021-11-08T15:42:17.4994159Z  33/239 Test   #6: rnp_tests.raw_elgamal_random_key_test_success .................................***Failed   28.66 sec
2021-11-08T15:42:17.5001386Z Note: Google Test filter = rnp_tests.raw_elgamal_random_key_test_success
2021-11-08T15:42:17.5002616Z [==========] Running 1 test from 1 test suite.
2021-11-08T15:42:17.5004267Z [----------] Global test environment set-up.
2021-11-08T15:42:17.5004912Z [----------] 1 test from rnp_tests
2021-11-08T15:42:17.5005421Z [ RUN      ] rnp_tests.raw_elgamal_random_key_test_success
2021-11-08T15:42:17.5006153Z [       OK ] rnp_tests.raw_elgamal_random_key_test_success (28593 ms)
2021-11-08T15:42:17.5007465Z [----------] 1 test from rnp_tests (28593 ms total)
2021-11-08T15:42:17.5008003Z 
2021-11-08T15:42:17.5008604Z [----------] Global test environment tear-down
2021-11-08T15:42:17.5009307Z [==========] 1 test from 1 test suite ran. (28594 ms total)
2021-11-08T15:42:17.5009918Z [  PASSED  ] 1 test.
2021-11-08T15:42:17.5010800Z ==68526==LeakSanitizer has encountered a fatal error.
2021-11-08T15:42:17.5011563Z ==68526==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
2021-11-08T15:42:17.5012571Z ==68526==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

**Review by ronaldtse — APPROVED** [review]
Thanks @ni4 . This is purely a CI change, so merging with 1 approval.

**Comment by ni4** [comment]
> Not sure why this is failing:
> 
> ```
> 2021-11-08T15:42:17.5010800Z ==68526==LeakSanitizer has encountered a fatal error.
> 2021-11-08T15:42:17.5011563Z ==68526==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
> 2021-11-08T15:42:17.5012571Z ==68526==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
> ```

I saw such issue few days ago, and never before. Looks like related to LeakSanitizer, let's see whether it will re-appear.

**Pull request merged**
