### PR TITLE
Add test case for unencrypted EdDSA secret key with leading zeroes.

### LINKED ISSUE #1812: Check whether RNP correctly handles cleartext EdDSA secret keys with leading zeroes.
## Description

More details and sample key are available in this GnuPG ticket: https://dev.gnupg.org/T5120
Even if everything works we should add test case to not allow regression in the future.

### PR DESCRIPTION
**Pull request by ni4**
It worked well, but still it's good to cover it.

Fixes #1812

### CODE REVIEW

**Review by antonsviridenko — APPROVED** [review]

**Review by andrey-utkin — APPROVED** [review]
LGTM.

Codecov is crazy, that report doesn't make sense. It claims to have compared it to a baseline commit which makes sense, but apparently it has really compared it with something different.

**Comment by ni4** [comment]
> Codecov is crazy, that report doesn't make sense. It claims to have compared it to a baseline commit which makes sense, but apparently it has really compared it with something different.

I thought so, but actually it isn't. See the PR #1817 - in CLI tests we use some random-generated input, which sometimes was hitting AEAD edge cases, and sometimes not. Will rebase as that PR is already merged.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@ni4 we're waiting for a rebase here, right?

**Comment by ni4** [comment]
@ronaldtse Actually not, but now I'm wondering why MSVC test fails, needs recheck so we don't miss something.

**Comment by ni4** [comment]
Okay, let's try to restart and see whether that helps. Don't see where it may crash/seems crash happens after the test's run.

**Comment by ni4** [comment]
Now it succeeded, so let's merge.

**Pull request merged**
