### PR TITLE
RIPEMD160 is now available by default since OpenSSL 3.0.7.

### LINKED ISSUE #1980: OpenSSL 3.0.7 adds RIPEMD160 to the default crypto provider
## Description

So we could need to slightly adjust changes, introduced by resolving issue #1880 

Changelog: https://www.openssl.org/news/cl31.txt

### PR DESCRIPTION
**Pull request by antonsviridenko**
Closes #1980

### CODE REVIEW

**Comment by ronaldtse** [comment]
@antonsviridenko don't we need a specific check to the OpenSSL engine to see if RIPEMD160 is included / available?

**Comment by antonsviridenko** [comment]
@ronaldtse these checks are already implemented in https://github.com/rnpgp/rnp/pull/1883

**Review by ronaldtse — APPROVED** [review]
Thank you @antonsviridenko !

**Comment by ni4** [comment]
> @ronaldtse these checks are already implemented in #1883

@antonsviridenko Changes from #1883 doesn't check whether specific algo is included into the default or legacy crypto provider. So for this case we should check in code for OpenSSL version >= 3.0.7, using the `OPENSSL_VERSION_NUMBER` define.

**Review by ni4 — CHANGES_REQUESTED** [review]
We should check for OpenSSL version, please see my comment.

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Comment by ni4** [comment]
@antonsviridenko Feel free to merge once CI is all green.

**Comment by antonsviridenko** [comment]
Don't know what's wrong with nix.

**Comment by ribose-jeffreylau** [comment]
Looks like we need to bump the action version to v22: https://github.com/cachix/install-nix-action/issues/183#issuecomment-1596385740

**Comment by ribose-jeffreylau** [comment]
@antonsviridenko CI is all green now.

**Pull request merged**
