### PR TITLE
Avoid concurrent test failures in /tmp

### PR DESCRIPTION
**Pull request by dkg**
When built in /tmp with a parallel run of the test suite, the same
filename can be clobbered by different tests.

With this patch, it builds and tests clean.

Closes: #1408

### CODE REVIEW

**Comment by ni4** [comment]
LGTM, but could you please create copy of this which merges into master instead of release?

**Comment by ronaldtse** [comment]
@dkg I've changed to the master branch -- could you help rebase your patch on top of master? Thanks!

**Comment by ni4** [comment]
@ronaldtse Probably it would be easier to close this PR and create a fresh one, WDYT? I can handle this, if needed.

**Comment by dkg** [comment]
I'm fine with either approach.  I have not done a ton of testing with the master branch (esp. compared to the `release/0.x` branch), but #1426 should target it more cleanly, so i'm closing this one.  hopefully the changes won't be any problem to backport.

**Pull request closed without merging**
