### PR TITLE
don't iterate when already past-the-end

### LINKED ISSUE #1252: Cannot increment list iterator which is already past-the-end
## Description

It was detected that `key_iter_next_key()` is sometimes called again even if the previous call returned `false`.
Visual C++ triggers runtime exception.
https://stackoverflow.com/questions/53471376/cannot-increment-end-list-iterator-run-time-error-visual-c
I suggest to fix by comparing the iterator to `end` prior to incrementing.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
Fixes #1252

### CODE REVIEW

**Comment by rrrooommmaaa** [comment]
@ni4 I have prepared refactoring of the code that handles `rnp_identifier_iterator_st.keyp` in a proper way but haven't pushed it yet. Instead, I added the code to throw an exception when trying to advance the iterator past the end. It turns out, some portions of `test_ffi_key_iter` fail now, Do you want me to copy this pieces into a separate test? And should I replace exception with some other way to track the error?

**Comment by ni4** [comment]
@rrrooommmaaa if I correctly understand you - FFI functions must not throw exceptions, and just check for errors/return corresponding error code. And unless there is a specific reason, behavior should not be changed, i.e. all old tests should be passing.

**Comment by rrrooommmaaa** [comment]
@ni4 My question was about this:
> However this would require a test, which reproduces the case(s) in which error may occur.
We already have `test_ffi_key_iter` test that fails on Windows. What other tests would you want to have?

**Comment by ni4** [comment]
@rrrooommmaaa Got it. Previously there was another code in this PR. Right now I think it would be more logical to close this PR and wait for MSVC changes finished and merged.

**Comment by rrrooommmaaa** [comment]
This issue will be fixed as part of #1232

**Pull request closed without merging**
