### PR TITLE
Use last encrypting subkey in rnp_key_export_autocrypt(). Closes #1470.

### LINKED ISSUE #1470: Fix inconsistency between rnp_key_export_autocrypt() and find_suitable_key().
## Description

Function find_suitable_key() was fixed in the PR #1318 to return latest encrypting subkey, however rnp_key_export_autocrypt() still returns first encrypting subkey. While it is possible to pick subkey automatically, it still should reuse find_suitable_key(). Some boolean flag could be added like 'no_primary', so it will search subkeys only.
May be related or implemented together with #1457

### PR DESCRIPTION
**Pull request by antonsviridenko**
`find_encrypting_subkey()` is removed, `find_suitable_key()` is used instead, for consistency. Now last subkey is returned instead of the first one. Test is updated accordingly.

### CODE REVIEW

**Comment by ni4** [comment]
@antonsviridenko Thanks! Could you please also add test case with encrypt+sign capable primary key (RSA for instance) + encrypting subkey, making sure that encrypting subkey is correctly returned?

P.S. "Closes #1470" in title would not work, it should be in the comment body.

**Comment by antonsviridenko** [comment]
@ni4 existing test case already uses encrypt+sign capable primary key

**Comment by ni4** [comment]
@antonsviridenko `key0-uid2` is limited to sign/certify via the userid certifications, you may see this in `rnp --list-packets`: 
```
...
:off 547: packet header 0xb409 (tag 13, len 9)
UserID packet
    id: key0-uid2
:off 558: packet header 0x88b9 (tag 2, len 185)
Signature packet
    version: 4
    type: 19 (Positive User ID certification)
    public key algorithm: 1 (RSA (Encrypt or Sign))
    hash algorithm: 2 (SHA1)
    hashed subpackets:
        :type 2, len 4
        signature creation time: 1500569846 (Thu Jul 20 19:57:26 2017)
        :type 27, len 1
        **key flags: 0x03 ( certify sign )**
```
You may generate such key using the gpg or writing some short code snippet utilising `rnp_op_generate_create()`, `rnp_op_generate_add_usage()` and so on. First one would be faster: `gpg --homedir .gpg --full-generate --expert` and choose 8.

**Comment by antonsviridenko** [comment]
hmm, I looked in rnpkeys --list-keys output, and it says `(Encrypt or Sign)`

```
pub   1024/RSA (Encrypt or Sign) 7bc6709b15c23a4a 2017-07-20 [SC]
      e95a3cbf583aa80a2ccc53aa7bc6709b15c23a4a
uid           key0-uid0
uid           key0-uid1
uid           key0-uid2
sub   1024/RSA (Encrypt or Sign) 1ed63ee56fadc34d 2017-07-20 [E]
      e332b27caf4742a11baa677f1ed63ee56fadc34d
sub   1024/DSA 1d7e8a5393c997a8 2017-07-20 [S] [EXPIRED 2017-11-20]
      c5b15209940a7816a7af3fb51d7e8a5393c997a8
sub   1024/RSA (Encrypt or Sign) 8a05b89fad5aded1 2017-07-20 [E]
      5cd46d2a0bd0b8cfe0b130ae8a05b89fad5aded1
```

**Comment by antonsviridenko** [comment]
how I supposed to see these restrictions as a normal user?

**Comment by ni4** [comment]
> how I supposed to see these restrictions as a normal user?

Hm, I see. We should change output a bit, I'll file an issue. `RSA (Encrypt or Sign)` is string, specifying the algorithm constant, there are also `RSA Encrypt-Only` and `RSA Sign-Only`, which are marked as deprecated in RFC 4880.
Real flags are printed as chars after the creation date: `[SC]` == sign, certify.

**Comment by antonsviridenko** [comment]
ok

**Comment by ni4** [comment]
@antonsviridenko Please rebase on the master to have ruby-rnp tests pass.

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Comment by antonsviridenko** [comment]
ping @ronaldtse

**Review by ronaldtse — APPROVED** [review]
LGTM, thanks @antonsviridenko !

**Pull request merged**
