### PR TITLE
Increase coverage for KBX and G10

### LINKED ISSUE #1997: Extend tests coverage on KBX/G10
## Description

As of Codecov report it should be possible to extend coverage on files related to KBX/G10.

### PR DESCRIPTION
**Pull request by antonsviridenko**
and fix some parsing issues. Closes #1997

### CODE REVIEW

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @antonsviridenko and @ni4 !

**Comment by antonsviridenko** [comment]
what tasks can I do next?

**Comment by ni4** [comment]
@antonsviridenko #2083 , #1980, #1786, #1643, #1611, #1609/#1857 or any other one you'd find appropriate :)

**Pull request merged**
