### PR TITLE
Add rnp_signature_get_features

### PR DESCRIPTION
**Pull request by kaie**

### CODE REVIEW

**Comment by ni4** [comment]
@kaie Thanks for the submission! Could you please add the following test calls (as I cannot push to your fork) to make codecov happier:
```
assert_rnp_failure(rnp_signature_get_features(NULL, &features));
assert_rnp_failure(rnp_signature_get_features(sig, NULL));
```

**Comment by kaie** [comment]
> @kaie Thanks for the submission! Could you please add the following test calls (as I cannot push to your fork) to make codecov happier:
> 
> ```
> assert_rnp_failure(rnp_signature_get_features(NULL, &features));
> assert_rnp_failure(rnp_signature_get_features(sig, NULL));
> ```

good suggestion, done

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Comment by ni4** [comment]
Thank you guys!
Two approvals == merge.

**Pull request merged**
