### PR TITLE
Fix Windows CI failures.

### LINKED ISSUE #2139: cli_tests-Encryption failure on Windows
After botan upgrade to 3.1 cli_tests-Encryption fails on Windows
It happens in 30% of cases but always with the following test and settings:  --aead --cipher AES192 

```
2023-10-28T19:09:54.7436902Z ======================================================================
2023-10-28T19:09:54.7437398Z ERROR: test_sym_encryption__rnp_aead (__main__.Encryption.test_sym_encryption__rnp_aead)
2023-10-28T19:09:54.7437619Z ----------------------------------------------------------------------
2023-10-28T19:09:54.7437779Z Traceback (most recent call last):
2023-10-28T19:09:54.7438272Z   File "D:\a\rnp\rnp\src\tests\cli_tests.py", line 4166, in test_sym_encryption__rnp_aead
2023-10-28T19:09:54.7438609Z     rnp_sym_encryption_rnp_aead(size, cipher, z, [aead, bits], GPG_AEAD)
2023-10-28T19:09:54.7439081Z   File "D:\a\rnp\rnp\src\tests\cli_tests.py", line 731, in rnp_sym_encryption_rnp_aead
2023-10-28T19:09:54.7439257Z     rnp_decrypt_file(enc, dst)
2023-10-28T19:09:54.7439653Z   File "D:\a\rnp\rnp\src\tests\cli_tests.py", line 402, in rnp_decrypt_file
2023-10-28T19:09:54.7439872Z     raise_err('rnp decryption failed', out + err)
2023-10-28T19:09:54.7440370Z   File "D:\a\rnp\rnp\src\tests\cli_common.py", line 39, in raise_err
2023-10-28T19:09:54.7440536Z     raise CLIError(msg, log)
2023-10-28T19:09:54.7440734Z cli_common.CLIError: rnp decryption failed
```

```
2023-10-28T19:09:54.7079341Z D:/a/rnp/rnp/build/src/rnp/rnp.exe rnp.exe --homedir C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\.rnp --bzip2 --aead --cipher AES192 --pass-fd 4 --passwords 1 -c C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\cleartext.txt --output C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\cleartext.enc
2023-10-28T19:09:54.7079545Z Working directory: D:\a\rnp\rnp\build\src\tests
2023-10-28T19:09:54.7079551Z 
2023-10-28T19:09:54.7079557Z 
2023-10-28T19:09:54.7081399Z D:/a/rnp/rnp/build/src/rnp/rnp.exe rnp.exe --homedir C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\.rnp --pass-fd 4 --decrypt C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\cleartext.enc --output C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpbo9at63q\cleartext.rnp
2023-10-28T19:09:54.7081605Z Working directory: D:\a\rnp\rnp\build\src\tests
2023-10-28T19:09:54.7081616Z 
2023-10-28T19:09:54.7081621Z 
2023-10-28T19:09:54.7081764Z rnp decryption failed
2023-10-28T19:09:54.7081771Z 
2023-10-28T19:09:54.7081867Z ERROR
```

### PR DESCRIPTION
**Pull request by ni4**
Fixes #2139

### CODE REVIEW

**Comment by ni4** [comment]
@maxirmx Do you have an idea why for windows-native runner cache hits for openssl backend, but always misses botan, taking 20m to install vcpkg packages? Thanks!

**Comment by maxirmx** [comment]
> @maxirmx Do you have an idea why for windows-native runner cache hits for openssl backend, but always misses botan, taking 20m to install vcpkg packages? Thanks!

@ni4, I guess it happens because there is no cache. Cache is created only if its job completes sucessfully and the latest botan runs either fails (test) or are cancelled. Caches are invalidated often because of vcpkg updates. Vcpkg does not have versions or releases so I am just fetching the latest version.

IMHO it would be difficult to fix this using GHA without local debugger.  I tried to run it locally but cli tests (python) can run in MSys environment only so I was not able to create any working environment.

If you think it is feasible I can fix the tests and go through it with debugger. It will probably take 2-3 days. Not sure I will be able to fix fast on my own the issue but at least we will know what is broken.

**Comment by ni4** [comment]
@maxirmx Thanks for the reply! Didn't know that cache is only submitted on successfull run. Actually with the latest iteration got much closer to the solution for the issue, now I (most likely) see point of failure. So hopefully few more iterations and got this resolved.
Don't have Windows environment at the moment, so this way seems to be faster.

**Comment by ni4** [comment]
Closing this as problem is on the Botan's side, on our side is aimed to be fixed via  PR #2148

**Pull request closed without merging**
