### PR TITLE
Check required OpenSSL features via CMake

### PR DESCRIPTION
**Pull request by ni4**
This PR adds CMake module which is aimed to check for required OpenSSL features availability.
Currently it doesn't change much, but could be updated later on to be able to enable/disable certain features depending on OpenSSL compile switches.

Fixes #1692

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thanks @ni4 !

**Comment by ronaldtse** [comment]
@maxirmx does it make sense to extract the CMake parts to a separate repo?

**Comment by maxirmx** [comment]
> @maxirmx does it make sense to extract the CMake parts to a separate repo?

IMHO it makes sense if/when you want to use it accross several projects

**Comment by ni4** [comment]
@ronaldtse I was thinking on adding OpenSSL module to the https://github.com/rnpgp/cmake-modules
May become useful for someone else.

**Comment by ronaldtse** [comment]
@ni4 would you like to move the code there first and then apply it here? Saves some additional work here.

**Comment by ni4** [comment]
@ronaldtse Done: https://github.com/rnpgp/cmake-modules/pull/6

**Comment by ronaldtse** [comment]
@ni4 merged in cmake-modules!

**Comment by ronaldtse** [comment]
@ni4 will you update this PR to use the newly extracted cmake module?

**Comment by ni4** [comment]
> @ni4 will you update this PR to use the newly extracted cmake module?

@ronaldtse Stuck a bit on https://github.com/rnpgp/cmake-modules/issues/7 , will update this PR once finished there. Probably would need to update module a bit.

**Comment by ronaldtse** [comment]
Got it, thanks @ni4 !

**Review by antonsviridenko — APPROVED** [review]

**Pull request merged**
