### PR TITLE
Add Ubuntu GHA workflow

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Test failures:

ubuntu / tests (normal, beta)
https://github.com/rnpgp/rnp/pull/980/checks?check_run_id=326820200

```sh
2019-11-30T04:43:08.8580879Z mv -f .deps/json_c_version.Tpo .deps/json_c_version.Plo
2019-11-30T04:43:08.8611479Z /bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c -o json_object_iterator.lo json_object_iterator.c
2019-11-30T04:43:08.8667554Z json_object.c: In function â€˜json_object_get_int64â€™:
2019-11-30T04:43:08.8668405Z json_object.c:554:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
2019-11-30T04:43:08.8669080Z   if (json_parse_int64(jso->o.c_string.str, &cint) == 0) return cint;
2019-11-30T04:43:08.8669374Z      ^
2019-11-30T04:43:08.8669608Z json_object.c:555:3: note: here
2019-11-30T04:43:08.8669827Z    default:
2019-11-30T04:43:08.8670043Z    ^~~~~~~
2019-11-30T04:43:08.9122510Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c json_object_iterator.c  -fPIC -DPIC -o .libs/json_object_iterator.o
2019-11-30T04:43:08.9315786Z cc1: all warnings being treated as errors
2019-11-30T04:43:08.9335388Z make[1]: *** [json_object.lo] Error 1
2019-11-30T04:43:08.9335982Z Makefile:574: recipe for target 'json_object.lo' failed
2019-11-30T04:43:08.9336581Z make[1]: *** Waiting for unfinished jobs....
2019-11-30T04:43:08.9423489Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c json_object_iterator.c -o json_object_iterator.o >/dev/null 2>&1
2019-11-30T04:43:08.9736194Z mv -f .deps/json_object_iterator.Tpo .deps/json_object_iterator.Plo
2019-11-30T04:43:08.9762094Z make[1]: Leaving directory '/home/runner/local-builds/json-c'
2019-11-30T04:43:08.9768833Z Makefile:638: recipe for target 'install-recursive' failed
2019-11-30T04:43:08.9773237Z make: *** [install-recursive] Error 1
2019-11-30T04:43:08.9791414Z ##[error]Process completed with exit code 2.
2019-11-30T04:43:08.9809185Z Cleaning up orphan processes
```


ubuntu / tests (sanitize, beta)
https://github.com/rnpgp/rnp/pull/980/checks?check_run_id=326820208

```
2019-11-30T04:43:09.2963173Z HEAD is now at f73605e Fix gpg-error.c for preprocessor use.
2019-11-30T04:43:09.2963271Z + popd
2019-11-30T04:43:09.2964380Z ~/local-builds/gpg ~/local-builds/gpg/gpg-build-scripts
2019-11-30T04:43:09.2964730Z + fold_end component.libgpg-error.fetch
2019-11-30T04:43:09.2964827Z + case "${_arg_folding_style}" in
2019-11-30T04:43:09.2964934Z + build_and_install
2019-11-30T04:43:09.2965037Z + local _sudo=
2019-11-30T04:43:09.2965139Z + [[ off = \o\n ]]
2019-11-30T04:43:09.2965405Z + pushd libgpg-error-git-f73605e
2019-11-30T04:43:09.2965675Z + [[ ! -f configure ]]
2019-11-30T04:43:09.2965957Z + fold_start component.libgpg-error.autogen
2019-11-30T04:43:09.2966062Z + case "${_arg_folding_style}" in
2019-11-30T04:43:09.2966171Z + ./autogen.sh
2019-11-30T04:43:09.2966528Z ~/local-builds/gpg/libgpg-error-git-f73605e ~/local-builds/gpg ~/local-builds/gpg/gpg-build-scripts
2019-11-30T04:43:09.6495782Z ./autogen.sh: 1: ./autogen.sh: msgmerge: not found
2019-11-30T04:43:09.6522115Z **Error**: `msgmerge' not installed or too old.
2019-11-30T04:43:09.6523059Z            Version 0.19.3 or newer is required.
2019-11-30T04:43:09.6523821Z            Note that this is part of `gettext'.
2019-11-30T04:43:09.6532768Z 
2019-11-30T04:43:09.6535088Z Note that you may use alternative versions of the tools by setting
2019-11-30T04:43:09.6535293Z autogen.sh: Stop.
2019-11-30T04:43:09.6535409Z the corresponding environment variables; see README.GIT for details.
2019-11-30T04:43:09.6535470Z 
2019-11-30T04:43:09.6559786Z ##[error]Process completed with exit code 1.
2019-11-30T04:43:09.6579301Z Cleaning up orphan processes
```

ubuntu / tests (coverage, beta, cli_tests)
https://github.com/rnpgp/rnp/pull/980/checks?check_run_id=326820217

```sh
2019-11-30T04:43:11.2055008Z mv -f .deps/json_c_version.Tpo .deps/json_c_version.Plo
2019-11-30T04:43:11.2082589Z /bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c -o json_object_iterator.lo json_object_iterator.c
2019-11-30T04:43:11.2258894Z json_object.c: In function â€˜json_object_get_int64â€™:
2019-11-30T04:43:11.2261152Z json_object.c:554:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
2019-11-30T04:43:11.2262332Z   if (json_parse_int64(jso->o.c_string.str, &cint) == 0) return cint;
2019-11-30T04:43:11.2263132Z      ^
2019-11-30T04:43:11.2264926Z json_object.c:555:3: note: here
2019-11-30T04:43:11.2265247Z    default:
2019-11-30T04:43:11.2265490Z    ^~~~~~~
2019-11-30T04:43:11.2682446Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c json_object_iterator.c  -fPIC -DPIC -o .libs/json_object_iterator.o
2019-11-30T04:43:11.3020929Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c json_object_iterator.c -o json_object_iterator.o >/dev/null 2>&1
2019-11-30T04:43:11.3392392Z mv -f .deps/json_object_iterator.Tpo .deps/json_object_iterator.Plo
2019-11-30T04:43:11.3429231Z /bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_tokener.lo -MD -MP -MF .deps/json_tokener.Tpo -c -o json_tokener.lo json_tokener.c
2019-11-30T04:43:11.3925604Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_tokener.lo -MD -MP -MF .deps/json_tokener.Tpo -c json_tokener.c  -fPIC -DPIC -o .libs/json_tokener.o
2019-11-30T04:43:11.4364508Z json_tokener.c: In function â€˜json_tokener_parse_exâ€™:
2019-11-30T04:43:11.4365188Z json_tokener.c:303:12: error: this statement may fall through [-Werror=implicit-fallthrough=]
2019-11-30T04:43:11.4365692Z          if (tok->flags & JSON_TOKENER_STRICT) {
2019-11-30T04:43:11.4366649Z             ^
2019-11-30T04:43:11.4366975Z json_tokener.c:308:7: note: here
2019-11-30T04:43:11.4367503Z        case '"':
2019-11-30T04:43:11.4367863Z        ^~~~
2019-11-30T04:43:11.7688400Z cc1: all warnings being treated as errors
2019-11-30T04:43:11.7727675Z make[1]: *** [json_object.lo] Error 1
2019-11-30T04:43:11.7728429Z Makefile:574: recipe for target 'json_object.lo' failed
2019-11-30T04:43:11.7728578Z make[1]: *** Waiting for unfinished jobs....
2019-11-30T04:43:11.7762410Z cc1: all warnings being treated as errors
2019-11-30T04:43:11.7787572Z Makefile:574: recipe for target 'json_tokener.lo' failed
2019-11-30T04:43:11.7788187Z make[1]: *** [json_tokener.lo] Error 1
2019-11-30T04:43:11.7791640Z make[1]: Leaving directory '/home/runner/local-builds/json-c'
2019-11-30T04:43:11.7794896Z Makefile:638: recipe for target 'install-recursive' failed
2019-11-30T04:43:11.7798611Z make: *** [install-recursive] Error 1
2019-11-30T04:43:11.7817216Z ##[error]Process completed with exit code 2.
2019-11-30T04:43:11.7841868Z Cleaning up orphan processes
```

**Comment by ronaldtse** [comment]
Remaining issue:

```
2019-11-30T09:52:11.2845552Z mv -f .deps/debug.Tpo .deps/debug.Plo
2019-11-30T09:52:11.2875051Z /bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object.lo -MD -MP -MF .deps/json_object.Tpo -c -o json_object.lo json_object.c
2019-11-30T09:52:11.3377606Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_c_version.lo -MD -MP -MF .deps/json_c_version.Tpo -c json_c_version.c  -fPIC -DPIC -o .libs/json_c_version.o
2019-11-30T09:52:11.3445240Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object.lo -MD -MP -MF .deps/json_object.Tpo -c json_object.c  -fPIC -DPIC -o .libs/json_object.o
2019-11-30T09:52:11.3580782Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_c_version.lo -MD -MP -MF .deps/json_c_version.Tpo -c json_c_version.c -o json_c_version.o >/dev/null 2>&1
2019-11-30T09:52:11.3792070Z mv -f .deps/json_c_version.Tpo .deps/json_c_version.Plo
2019-11-30T09:52:11.3822706Z /bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c -o json_object_iterator.lo json_object_iterator.c
2019-11-30T09:52:11.3865031Z json_object.c: In function â€˜json_object_get_int64â€™:
2019-11-30T09:52:11.3866074Z json_object.c:554:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
2019-11-30T09:52:11.3866442Z   if (json_parse_int64(jso->o.c_string.str, &cint) == 0) return cint;
2019-11-30T09:52:11.3866557Z      ^
2019-11-30T09:52:11.3867064Z json_object.c:555:3: note: here
2019-11-30T09:52:11.3867532Z    default:
2019-11-30T09:52:11.3867859Z    ^~~~~~~
2019-11-30T09:52:11.4390714Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c json_object_iterator.c  -fPIC -DPIC -o .libs/json_object_iterator.o
2019-11-30T09:52:11.4496421Z cc1: all warnings being treated as errors
2019-11-30T09:52:11.4519234Z make[1]: *** [json_object.lo] Error 1
2019-11-30T09:52:11.4520344Z Makefile:574: recipe for target 'json_object.lo' failed
2019-11-30T09:52:11.4520799Z make[1]: *** Waiting for unfinished jobs....
2019-11-30T09:52:11.4765700Z libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Werror -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -std=gnu99 -D_GNU_SOURCE -D_REENTRANT -fno-omit-frame-pointer -g -MT json_object_iterator.lo -MD -MP -MF .deps/json_object_iterator.Tpo -c json_object_iterator.c -o json_object_iterator.o >/dev/null 2>&1
2019-11-30T09:52:11.5108457Z mv -f .deps/json_object_iterator.Tpo .deps/json_object_iterator.Plo
2019-11-30T09:52:11.5133575Z make[1]: Leaving directory '/home/runner/local-builds/json-c'
2019-11-30T09:52:11.5146834Z make: *** [install-recursive] Error 1
2019-11-30T09:52:11.5147126Z Makefile:638: recipe for target 'install-recursive' failed
2019-11-30T09:52:11.5164949Z ##[error]Process completed with exit code 2.
2019-11-30T09:52:11.5180966Z Cleaning up orphan processes
```

**Comment by rrrooommmaaa** [comment]
`ubuntu-latest` is Ubuntu 19. So we don't have to build `botan2` (and `libjson-c`).
I can see that they are being built anyway in `ci/install.sh`.
Should we rule the build out?

**Comment by ronaldtse** [comment]
> `ubuntu-latest` is Ubuntu 19. So we don't have to build `botan2` (and `libjson-c`).
> I can see that they are being built anyway in `ci/install.sh`.
> Should we rule the build out?

@dewyatt can you give an answer here? Thanks.

**Comment by ronaldtse** [comment]
@rrrooommmaaa according to GHA documentation `ubuntu-latest` is still 18.04. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners

Has it really been changed to 19?

In the logs, I'm still seeing packages from `bionic` which is 18.04:
```
2019-12-04T13:46:45.3577440Z Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
```

Ubuntu 19 is Disco Dingo (http://releases.ubuntu.com/19.04/)

**Comment by ronaldtse** [comment]
Anyway, since it already works, merging this first.

**Pull request merged**
