### PR TITLE
Github Actions: Update some sub-actions to v2, and do not use deprecated ::set-env.

### LINKED ISSUE #1327: GHA: `set-env` command is deprecated and will be disabled soon.
## Description

[warning]The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

### PR DESCRIPTION
**Pull request by ni4**
Fixes #1327

### CODE REVIEW

**Comment by ronaldtse** [comment]
This looks good, except that GnuPG pinentry is failing to compile on macOS:

```
pinentry-curses.c:479:8: error: implicit declaration of function 'addnwstr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
3056
              ADDCH (start[i]);
3057
              ^
3058
pinentry-curses.c:116:18: note: expanded from macro 'ADDCH'
3059
#define ADDCH(x) addnwstr (&x, 1);
3060
                 ^
3061
pinentry-curses.c:479:8: note: did you mean 'addnstr'?
3062
pinentry-curses.c:116:18: note: expanded from macro 'ADDCH'
3063
#define ADDCH(x) addnwstr (&x, 1);
3064
                 ^
3065
/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/curses.h:523:28: note: 'addnstr' declared here
3066
extern NCURSES_EXPORT(int) addnstr (const char *, int);                 /* generated */
3067
                           ^
3068
pinentry-curses.c:482:6: error: implicit declaration of function 'addnwstr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
3069
            ADDCH (start[len - 1]);
3070
            ^
3071
pinentry-curses.c:116:18: note: expanded from macro 'ADDCH'
3072
#define ADDCH(x) addnwstr (&x, 1);
3073
                 ^
3074
pinentry-curses.c:515:7: error: implicit declaration of function 'addnwstr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
3075
                    ADDCH (*p);
3076
                    ^
3077
pinentry-curses.c:116:18: note: expanded from macro 'ADDCH'
3078
#define ADDCH(x) addnwstr (&x, 1);
3079
                 ^
3080
pinentry-curses.c:551:8: error: implicit declaration of function 'addnwstr' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
3081
              ADDCH (*(p++));
3082
              ^
3083
pinentry-curses.c:116:18: note: expanded from macro 'ADDCH'
3084
#define ADDCH(x) addnwstr (&x, 1);
3085
                 ^
3086
pinentry-curses.c:866:25: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
3087
      screen = newterm (tty_type, ttyfo, ttyfi);
3088
                        ^~~~~~~~
3089
/Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/curses.h:658:62: note: passing argument to parameter here
3090
extern NCURSES_EXPORT(SCREEN *) newterm (NCURSES_CONST char *,FILE *,FILE *);   /* implemented */
3091
                                                             ^
3092
1 warning and 4 errors generated.
3093
make[2]: *** [libpinentry_curses_a-pinentry-curses.o] Error 1
3094
make[1]: *** [all-recursive] Error 1
3095
make: *** [all] Error 2
3096
Error: Process completed with exit code 2.
```

https://github.com/rnpgp/rnp/pull/1344/checks?check_run_id=1423831619

**Comment by ni4** [comment]
@ronaldtse Yeah, seems it messes up with wide char/single char. Will try to figure it out.

**Comment by ni4** [comment]
@dewyatt @ronaldtse Does the solution with macOS build/curses looks good, or there could be better approach?

**Review by ronaldtse — APPROVED** [review]
LGTM, thanks @ni4 !

**Comment by ronaldtse** [comment]
> @dewyatt @ronaldtse Does the solution with macOS build/curses looks good, or there could be better approach?

There may be a better approach but it's more important to first merge this in. Thanks!

**Comment by ronaldtse** [comment]
Merging since this is CI only.

**Pull request merged**
