### PR TITLE
Test partial length packet edge cases

### LINKED ISSUE #939: Check partial packet length edge cases.
## Description

Following cases should be checked:
- partial packet length for key/signature packets (must not be allowed to load).
- largest possible partial packet length (1Gb), cut down to reasonable size of course.
- 0-size last chunk length (is allowed).
- less then 512 byte size first chunk (should not be allowed).
- possibly other cases, see rfc4880-bis

This would require to modify some existing packet data and attempt to parse those via FFI calls.
Separate test file should be added to rnp_tests suite.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
Closes #939

### CODE REVIEW

**Comment by ronaldtse** [comment]
Agree with @ni4 , @rrrooommmaaa can you help consolidate the commits and give it a good name? Thanks!

**Comment by ronaldtse** [comment]
@rrrooommmaaa you don't need to close the PR, you can just "force push" to your PR branch, and the PR will be updated. Thanks.

**Comment by rrrooommmaaa** [comment]
@ronaldtse I force-pushed it yesterday before your comment, but can't remove 'Change requested' flag

**Comment by ronaldtse** [comment]
@rrrooommmaaa because the change requested flag can only be removed by the reviewer. Next time you can just ping us and we can resolve the review comment instead of opening a new PR.

**Pull request closed without merging**
