### PR TITLE
Remove 3DES and SHA1 from the default key preferences.

### LINKED ISSUE #1565: Remove 3DES and SHA1 from the default generated key preferences.
## Description

While SHA1 is must not to use, 3DES is a bit obsolete and replaced by AES.

### PR DESCRIPTION
**Pull request by ni4**
Fixes #1565

### CODE REVIEW

**Comment by ronaldtse** [comment]
Seems that Python homebrew is failing for some reason.

```
2021-11-30T11:11:28.0973540Z [34m==>[0m [1mPouring python@3.9--3.9.9.catalina.bottle.tar.gz[0m
2021-11-30T11:11:28.0974670Z [34m==>[0m [1m/usr/local/Cellar/python@3.9/3.9.9/bin/python3 -m ensurepip[0m
2021-11-30T11:11:28.0975780Z [34m==>[0m [1m/usr/local/Cellar/python@3.9/3.9.9/bin/python3 -m pip install -v --no-deps -[0m
2021-11-30T11:11:28.0976660Z [34m==>[0m [1mCaveats[0m
2021-11-30T11:11:28.0977100Z Python has been installed as
2021-11-30T11:11:28.0977530Z   /usr/local/bin/python3
2021-11-30T11:11:28.0977780Z 
2021-11-30T11:11:28.0978670Z Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
2021-11-30T11:11:28.0979880Z `python3`, `python3-config`, `pip3` etc., respectively, have been installed into
2021-11-30T11:11:28.0980550Z   /usr/local/opt/python@3.9/libexec/bin
2021-11-30T11:11:28.0980860Z 
2021-11-30T11:11:28.0981240Z You can install Python packages with
2021-11-30T11:11:28.0981690Z   pip3 install <package>
2021-11-30T11:11:28.0982580Z They will install into the site-package directory
2021-11-30T11:11:28.0983500Z   /usr/local/lib/python3.9/site-packages
2021-11-30T11:11:28.0983840Z 
2021-11-30T11:11:28.0984370Z tkinter is no longer included with this formula, but it is available separately:
2021-11-30T11:11:28.0985380Z   brew install python-tk@3.9
2021-11-30T11:11:28.0985680Z 
2021-11-30T11:11:28.0986570Z See: https://docs.brew.sh/Homebrew-and-Python
2021-11-30T11:11:28.0987480Z [34m==>[0m [1mSummary[0m
2021-11-30T11:11:28.0990870Z 🍺  /usr/local/Cellar/python@3.9/3.9.9: 3,080 files, 55MB
2021-11-30T11:11:28.0991880Z [34m==>[0m [1mRunning `brew cleanup python@3.9`...[0m
2021-11-30T11:11:28.0992660Z Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
2021-11-30T11:11:28.0993330Z Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
2021-11-30T11:11:28.0993930Z Removing: /usr/local/Cellar/python@3.9/3.9.8... (3,080 files, 55MB)
2021-11-30T11:11:28.0994990Z Removing: /Users/runner/Library/Caches/Homebrew/python@3.9--3.9.8... (13.9MB)
2021-11-30T11:11:28.0996100Z [31mError:[0m undefined method `bottled?' for #<Dependency: "httpd" [:build, :test]>
2021-11-30T11:11:28.0997210Z [1mDo not report this issue until you've run `brew update` and tried again.[0m
2021-11-30T11:11:28.0998420Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/delegate.rb:83:in `all?'
2021-11-30T11:11:28.1000590Z /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
2021-11-30T11:11:28.1001920Z /usr/local/Homebrew/Library/Homebrew/upgrade.rb:282:in `block in check_installed_dependents'
2021-11-30T11:11:28.1003470Z /usr/local/Homebrew/Library/Homebrew/upgrade.rb:281:in `each'
2021-11-30T11:11:28.1004640Z /usr/local/Homebrew/Library/Homebrew/upgrade.rb:281:in `partition'
2021-11-30T11:11:28.1005810Z /usr/local/Homebrew/Library/Homebrew/upgrade.rb:281:in `check_installed_dependents'
2021-11-30T11:11:28.1007030Z /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:207:in `upgrade_outdated_formulae'
2021-11-30T11:11:28.1008180Z /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:110:in `upgrade'
2021-11-30T11:11:28.1009190Z /usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
2021-11-30T11:11:28.1010100Z [31mUpgrading python has failed![0m
2021-11-30T11:11:28.1011100Z [31mHomebrew Bundle failed! 1 Brewfile dependency failed to install.[0m
2021-11-30T11:11:28.1057610Z ##[error]Process completed with exit code 1.
```

**Comment by ni4** [comment]
> Seems that Python homebrew is failing for some reason.

Yeah, another happy hours from homebrew :) Will wait for a while to see whether issue fixes itself/google search and issue trackers got populated.

**Review by antonsviridenko — APPROVED** [review]

**Comment by ribose-jeffreylau** [comment]
Homebrew Python issue has been fixed for now.  Codecov seems to fail, however...

**Comment by ni4** [comment]
@ribose-jeffreylau Thanks! Strange, that brew update didn't work here: https://github.com/ni4/rnp/pull/17/files
Will rebase, that should make codecov happier.

**Comment by ribose-jeffreylau** [comment]
> @ribose-jeffreylau Thanks! Strange, that brew update didn't work here: https://github.com/ni4/rnp/pull/17/files Will rebase, that should make codecov happier.

That is strange indeed!  Maybe homebrew changed some time in between...  In which case the `brew update` is not actually the solution.  Doesn't hurt to leave it in though I guess :p

**Comment by ni4** [comment]
@ronaldtse ping for review! All is green now.

**Comment by ni4** [comment]
@ronaldtse Ping again :) Could you please review this so we can merge it? Thanks!

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @ni4 and sorry for the delay! Didn't realise until your ping...

**Pull request merged**
