### PR TITLE
Fix possible crash of CLI utilities when HOME is not set.

### PR DESCRIPTION
**Pull request by ni4**
As title says.

### CODE REVIEW

**Comment by antonsviridenko** [comment]
As homedir is important, maybe it's also makes sense to check if it exists and is accessible? Otherwise LGTM

**Review by antonsviridenko — APPROVED** [review]

**Review by rrrooommmaaa — COMMENTED** [review]
there are a couple of other places with getenv("HOME"). Should we fix them too?
`tests/support.cpp:579` looks especially suspicious.

**Comment by ni4** [comment]
> `tests/support.cpp:579` looks especially suspicious.

This one just for tests and will not cause problems since we set HOME explicitly in `rnp_tests.cpp`: 
`EXPECT_EQ(0, setenv("HOME", m_dir, 1));`.

One in `rnp_cfg_set_defkey` will not cause problems as well, just will not found gnupg's conf file.

**Review by rrrooommmaaa — APPROVED** [review]
LGTM.
I guess we're waiting for @ni4 response to Anton's question.

**Comment by ni4** [comment]
> As homedir is important, maybe it's also makes sense to check if it exists and is accessible? Otherwise LGTM

I think this should be separated as another issue, will file it now.

**Comment by ni4** [comment]
@antonsviridenko Is it good to merge now?

**Pull request merged**
