### PR TITLE
Feature/link shellcheck

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP Spaces around = are quite dangerous in shell, I’d prefer keeping SC2191.

**Comment by CAMOBAP** [comment]
@ribose-jeffreylau @ni4 should I "squash" several commits in PR to a single one before merge? Or just rebase will be enough?

**Comment by ronaldtse** [comment]
> should I "squash" several commits in PR to a single one before merge? Or just rebase will be enough?

Would be better if we squash together commits that are meant to be together. For example if you have commits that correct/fix previous commits, they should be squashed so that the commit is "wholesome" itself.

**Comment by ronaldtse** [comment]
@CAMOBAP if possible let's not have exceptions for shellcheck, it's just hard to manage them in the future. Thanks!

**Comment by CAMOBAP** [comment]
Thanks, squashed+rebased, waiting for CI to pass

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP @ribose-jeffreylau @ni4 !

**Pull request merged**
