### PR TITLE
Fix incorrect key expiration calculation.

### PR DESCRIPTION
**Pull request by ni4**
This fixes previously uncovered case with non-zero key expiration time from direct-key signature with zero from primary uid certification.

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thanks @ni4!

**Review by antonsviridenko — COMMENTED** [review]
I see that changes in https://github.com/rnpgp/rnp/pull/1529 are identical to this one, probably one of PR-s was pushed by mistake twice.

**Comment by antonsviridenko** [comment]
Or almost identical, except "case 15"...

**Comment by ni4** [comment]
@antonsviridenko answered in #1529 - that one will be rebased on this one. Is this look good to you? Thanks!

**Review by antonsviridenko — APPROVED** [review]

**Pull request merged**
