### PR TITLE
ci: Add CentOS8 support

### PR DESCRIPTION
**Pull request by ribose-jeffreylau**
This PR refactors the pipeline scripts <s>(with ideas taken from #1459 so as to minimize merge conflicts at a later stage for either branch)</s><b>(done)</b> in order to consolidate common build and install routines.

A pipeline for CentOS 8 has been added<s>, as well as for packaging RPMs in various CentOS and Fedora versions</s>.

<s>Signing</s><b>Support for building</b> of RPM packages will be added in a separate PR after this PR has been merged.

### CODE REVIEW

**Comment by ribose-jeffreylau** [comment]
# Issues encountered

## Fedora 33

###  tests (normal/sanitize/coverage, stable/beta, *) 

```
<snip>
+ make
signal.c: In function ‘get_signal_name’:
signal.c:86:22: warning: unused parameter ‘signum’ [-Wunused-parameter]
   86 | get_signal_name( int signum )
      |                  ~~~~^~~~~~
In file included from sysutils.c:73:
/tmp/rnp-local-installs/gpg-install/include/npth.h:220:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
  220 | #if _NPTH_EXPOSE_RWLOCK_API
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/rnp-local-installs/gpg-install/include/npth.h:220:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
signal.c: In function ‘get_signal_name’:
signal.c:86:22: warning: unused parameter ‘signum’ [-Wunused-parameter]
   86 | get_signal_name( int signum )
      |                  ~~~~^~~~~~
In file included from exechelp-posix.c:56:
/tmp/rnp-local-installs/gpg-install/include/npth.h:220:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
  220 | #if _NPTH_EXPOSE_RWLOCK_API
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/rnp-local-installs/gpg-install/include/npth.h:220:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
In file included from call-gpg.c:25:
/tmp/rnp-local-installs/gpg-install/include/npth.h:220:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
  220 | #if _NPTH_EXPOSE_RWLOCK_API
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/rnp-local-installs/gpg-install/include/npth.h:220:5: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
/usr/bin/ld: libcommon.a(libcommon_a-iobuf.o):(.bss+0x0): multiple definition of `iobuf_debug_mode'; t-iobuf.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1047: t-iobuf] Error 1
make[2]: *** [Makefile:954: all] Error 2
make[1]: *** [Makefile:615: all-recursive] Error 1
make: *** [Makefile:535: all] Error 2
```

###  pkgconfig-cmake-target (*)

```
<snip>
Scanning dependencies of target encrypt
Scanning dependencies of target decrypt
[ 65%] Building C object src/examples/CMakeFiles/encrypt.dir/encrypt.c.o
[ 67%] Building C object src/examples/CMakeFiles/decrypt.dir/decrypt.c.o
[ 68%] Linking C executable decrypt
[ 70%] Linking C executable encrypt
/usr/bin/ld: ../lib/librnp.so.0.0.0: undefined reference to `Botan::HashFunction::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ../lib/librnp.so.0.0.0: undefined reference to `Botan::HashFunction::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/examples/CMakeFiles/decrypt.dir/build.make:108: src/examples/decrypt] Error 1
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/Makefile2:244: src/examples/CMakeFiles/decrypt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [src/examples/CMakeFiles/encrypt.dir/build.make:108: src/examples/encrypt] Error 1
make[1]: *** [CMakeFiles/Makefile2:217: src/examples/CMakeFiles/encrypt.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```

## CentOS 8

###  pkgconfig-cmake-target (*)

```
<snip>
Scanning dependencies of target encrypt
[ 60%] Building C object src/examples/CMakeFiles/encrypt.dir/encrypt.c.o
[ 61%] Linking C executable encrypt
../lib/librnp.so.0.0.0: undefined reference to `Botan::HashFunction::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: mode elf_x86_64
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crt1.o
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crti.o
/usr/lib/gcc/x86_64-redhat-linux/8/crtbegin.o
CMakeFiles/encrypt.dir/encrypt.c.o
../lib/librnp.so.0.0.0
/usr/lib64/libbotan-2.so
/usr/lib64/libjson-c12.so
/usr/lib64/libbz2.so
/usr/lib64/libz.so
/lib64/libgcc_s.so.1
/lib64/libc.so.6
(/usr/lib64/libc_nonshared.a)elf-init.oS
/lib64/ld-linux-x86-64.so.2
/lib64/ld-linux-x86-64.so.2
/lib64/libgcc_s.so.1
/usr/lib/gcc/x86_64-redhat-linux/8/crtend.o
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crtn.o
/usr/bin/ld: link errors found, deleting executable `encrypt'
collect2: error: ld returned 1 exit status
make[2]: *** [src/examples/CMakeFiles/encrypt.dir/build.make:89: src/examples/encrypt] Error 1
make[1]: *** [CMakeFiles/Makefile2:101: src/examples/CMakeFiles/encrypt.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

### tests(normal, stable)

```
  4/217 Test #214: cli_tests-Misc ................................................................***Failed   64.61 sec
```

### tests (coverage, beta, cli_tests)

```
 3/11 Test #208: cli_tests-Misc ...................***Failed   85.46 sec
```

**Comment by rrrooommmaaa** [comment]
Sorry, I accidentally cancelled a couple of your tests

**Comment by ribose-jeffreylau** [comment]
@rrrooommmaaa no big deal, thanks for letting me know though.  I once cancelled a scheduled coverity scan, so I just let it run again next time 🤣

**Comment by ni4** [comment]
@rrrooommmaaa @ribose-jeffreylau Btw, there is some limit on simultaneous CI workers, like 15 or 20. To make things faster you may run CI experiments on your own forks (however, Cirrus will not be run in such case).

As a side effect repository subscribers will not receive email on each push ;-)

**Comment by ribose-jeffreylau** [comment]
@ni4 Nice trick!  Thanks for the tips.  I'll try using my own fork.

**Comment by rrrooommmaaa** [comment]
> To make things faster you may run CI experiments on your own forks (however, Cirrus will not be run in such case).

I guess it works only on Enterprise accounts

**Comment by ni4** [comment]
> I guess it works only on Enterprise accounts

Nope, I used this approach multiple times on my account, see for instance: https://github.com/ni4/rnp/pull/15

**Comment by ribose-jeffreylau** [comment]
There are unresolved build issues in the `pkg-config` tests for CentOS 8, but I think they belong in a separate issue.

Closes #1440 .

**Comment by ribose-jeffreylau** [comment]
On a slightly related note, tests for ruby-rnp would always run out of memory on the GitHub Actions on my own forks.  I had to push to this PR in order to verify that those tests actually pass.

**Review by ni4 — APPROVED** [review]
LGTM, thanks! However we should not leave failing tests. Probably remove those from centos8 run and create issue to fix those later, if there is no quick solution right now?

**Comment by ribose-jeffreylau** [comment]
@ni4 Yes, that sounds good.  I'll do that.  Cheers!

**Review by ronaldtse — APPROVED** [review]
LGTM, thanks @ribose-jeffreylau !

**Comment by ni4** [comment]
Ping @dewyatt for review )

**Comment by ronaldtse** [comment]
Merging for now!

**Comment by ronaldtse** [comment]
Thanks @ribose-jeffreylau @ni4 !

**Pull request merged**
