### PR TITLE
Fix typo --hom in test_rnpkeys_lists

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Review by antonsviridenko — APPROVED** [review]

**Review by ronaldtse — APPROVED** [review]
Thank you @jirutka -- what a great find 🤦 👍

**Comment by ni4** [comment]
@jirutka Thanks! Actually, it worked with `--hom` as `getopt_long` allow partial command names.

**Comment by jirutka** [comment]
> it worked with `--hom` as `getopt_long` allow partial command names.

No, it did not, that’s how I found it. That’s glibc-specific behaviour, `getopt_long` on musl libc doesn’t allow partial command names.

**Comment by ni4** [comment]
Didn't know about the musl, thanks. Probably we should add some CI runner on top of musc libc.

**Pull request merged**
