### PR TITLE
spelling cleanup (release/0.x branch)

### PR DESCRIPTION
**Pull request by dkg**
There are no substantive changes here, just orthographic improvements.

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
LGTM, thanks @dkg !

**Comment by dewyatt** [comment]
Historically we don't merge directly to the release branches, we hit master and then it filters into the next release. Personally I'd prefer to stick to that and just do a point release to get these changes out there.

**Comment by ni4** [comment]
Yeah, let's better make 0.14.1 release once all PRs are merged. @dkg will this work for you?

**Comment by dkg** [comment]
sure, whatever works for you.  I've been proposing changes to the release branch because that's what i've been working on building for debian, and not every change I've proposed applies cleanly to the master branch.   i don't really get the "filtering" process you describe, between the master branch and the release branch, because they appear to share no git history.

i'm not really familiar working with the `git cherry` process encouraged in `docs/develop/release-workflow.adoc`, but i'll try to make future PRs to the master branch.

A 0.14.1 release (or 0.15.0, or whatever you like) with the proposed changes merged/cherry-picked would be great, thanks ☺

**Comment by ronaldtse** [comment]
This PR is now incorporated in #1449 together with other documentation updates. Thank you for the continuous contributions @dkg !

**Pull request closed without merging**
