### PR TITLE
Fix updating of key expiration for keys with multiple uids.

### LINKED ISSUE #1497: Update self-certifications for all userids in pgp_key_set_expiration().
## Description

Currently we update expiration only for the latest self-signature, while we should update latest self-signature for all uids (and direct-key sigs as well). This may cause the problem like the one described here: https://bugzilla.mozilla.org/show_bug.cgi?id=1704182

### PR DESCRIPTION
**Pull request by ni4**
Main purpose of this PR was to fix issue #1497, however due to internal changes it also touches issues #1311, #1316 and #1315. Those would be closed with a separate PR which extends test coverage.

Now key expiration/flags behaviour would be changed:
- first we'll look for key expiration from the direct-key signature
- then for the latest self-certification for the primary uid (if any), and pick the more strict of both.
- in other cases we'll pick the latest self-signature from the any userid.

Same would apply to the key flags.

Also this PR fixes problems, found in `pgp_key_t::del_uid()` and `pgp_key_t::is_expired()`.

Fixes #1497

### CODE REVIEW

**Comment by ni4** [comment]
@ribose-jeffreylau Do you have any quick idea why all centos7/8 buids are failing? Nothing seem to be changed since #1456 was merged, but it worked well.

**Comment by ronaldtse** [comment]
@ni4 I believe @ribose-jeffreylau will revert tomorrow since it's holiday today, thanks!

**Comment by ribose-jeffreylau** [comment]
@ni4 @ronaldtse Will be fixed in #1503.

**Comment by ronaldtse** [comment]
Rebased on latest master.

**Comment by ronaldtse** [comment]
The tests are still failing here; I wonder if this has something to do with the build cache?

**Comment by ribose-jeffreylau** [comment]
It does look like a build cache issue.  I'm creating a fix here in #1504 .

**Comment by ni4** [comment]
Thanks, @ribose-jeffreylau !

**Comment by ni4** [comment]
@ribose-jeffreylau @ronaldtse Could we just create Docker containers with all installed pre-requisites, and use them (updating periodically) for CI instead of running complicated scripts each time/spending time on debugging?

**Comment by ronaldtse** [comment]
@ni4 agree with the approach. 

@CAMOBAP would you happen to have time on this task?

**Review by ronaldtse — APPROVED** [review]

**Comment by antonsviridenko** [comment]
src/tests/data/test_key_edge_cases/alice-3-uids-primary-boris.pgp

This file is added to the repo but not used anywhere in the tests code

**Comment by ni4** [comment]
> src/tests/data/test_key_edge_cases/alice-3-uids-primary-boris.pgp
> This file is added to the repo but not used anywhere in the tests code

@antonsviridenko  Yeah, I had plans to use it in another PR to extend tests coverage. Do you think that having it in the repository may cause any issues (except additional data storage :) ) ?

**Review by antonsviridenko — APPROVED** [review]
ok then

**Pull request merged**
