### PR TITLE
Renamed master to main or added handling of main branch as necessary

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@maxirmx please ping me when we are ready to switch to `main`, I will make the change in GitHub repo settings.

**Comment by maxirmx** [comment]
I think it is ready though it is possible that I missed something and further adjustment will be required

When branch is renamed and GitHub repo settings are changed we may need to change settings in codecov and coverity projects as well

**Review by ronaldtse — APPROVED** [review]
Thank you @maxirmx ! I will make the branch change after merge.

**Comment by ronaldtse** [comment]
Merging with 1 approval for CI changes.

**Pull request merged**
