### PR TITLE
Added the --keyring option to support custom keyring names.

### LINKED ISSUE #70: Rnpkeys : user is unable to create/append keys to custom keyring.
The user is unable to create new keys in a custom user provided keyring. 
`usage: ./rnpkeys --generate-key --keyring=max`
expected output: new keyring with name "maxpub & maxsec" is created in the HOMEDIR.
Test case; `rnpkeys_generatekey_verifykeyRingOptions`

### PR DESCRIPTION
**Pull request by joke325**
Closes #70

### CODE REVIEW

**Comment by dewyatt** [comment]
I haven't looked at this much, but personally I don't think I'd be satisfied with this approach.
1) `rnp_compose2` is not a very descriptive name.
2) `rnp_compose2` looks over-complicated and it's trivial to make it segfault.
3) We already have `rnp_compose_path` and `paths_concat`. We need to start using `std::filesystem::path` et al and drop this stuff, not add more of it. (but catch those pesky exceptions)

**Comment by joke325** [comment]
@dewyatt I didn't observe any exceptions and it works with GPG21

**Comment by dewyatt** [comment]
> @dewyatt I didn't observe any exceptions and it works with GPG21

The exceptions I was referring to were just basic STL ones, but it looks like we already have this issue in the code base, so we can track that separately.

I think my concern with GPG21 was that it will create keyrings that aren't readily usable with gpg, like `<prefix>private-keys-v1.d`. Our `--keyring` option is pretty different from gpg's overall. That may be fine though. @ni4 @ronaldtse opinions?

**Comment by ni4** [comment]
@dewyatt GnuPG documentation tells `--secret-keyring file
This is an obsolete option and ignored. All secret keys are stored in the private-keys-v1.d directory below the GnuPG home directory.`, so we definitely should not use prefix for this one.

At first we should strictly define what actually `--keyring` option does. If it just adds prefix, then it should be called `--keyring-prefix`. However, then we would not be able to use keyring files with different extensions or endings, like pubring.pgp/pubkeys.asc/pubring.gpg, whatever else.
If it will have full keyring path, then we should also use `--secret-keyring` option.

Another thing - for GnuPG --keyring seems stackable, and has additionally --default-keyring option.

And I would definitely avoid adding new lines of tricky C code, and use std::string instead.

**Comment by joke325** [comment]
MohitKumarAgniotri on May 6, 2017 wrote:
> The user is unable to create new keys in a custom user provided keyring.
> usage: ./rnpkeys --generate-key --keyring=max
> expected output: new keyring with name "maxpub & maxsec" is created in the HOMEDIR.

@ni4 @dewyatt nor @ronaldtse  didn't protest about the description of expected functionality.

The current PR just adds the prefix, in addition it can contain a relative or absolute path to the keyring.

@ni4 where and how I should use the std::string?

**Comment by dewyatt** [comment]
> MohitKumarAgniotri on May 6, 2017 wrote:
> 
> > The user is unable to create new keys in a custom user provided keyring.
> > usage: ./rnpkeys --generate-key --keyring=max
> > expected output: new keyring with name "maxpub & maxsec" is created in the HOMEDIR.
> 
> @ni4 @dewyatt nor @ronaldtse didn't protest about the description of expected functionality.

When starting on a 3 year old issue, I'd say it's prudent to re-evaluate and check on whether things have changed. Sometimes we have higher priorities and things slip through the cracks. :(

> 
> The current PR just adds the prefix, in addition it can contain a relative or absolute path to the keyring.
> 
> @ni4 where and how I should use the std::string?

Generally if you find yourself using `strcpy`/`strcat`/`str*()`/`char*`, consider using a `std::string`. It does introduce exception concerns and most of our code is not exception-safe, but that's an issue we need to tackle regardless.

**Comment by ni4** [comment]
Let's close this as not releveant anymore: we have `--homedir` and `--keyfile` options, which should be sufficient for all uses. If some edge case is not covered - we'd create a separate issue/PR.

**Pull request closed without merging**
