### PR TITLE
MSVC sanitizer build

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
Created Windows runner with ASAN enbled; fixed memory corruption as described in https://github.com/rnpgp/rnp/issues/2152 and some annoying warning.
I was not able to run cli_test in native environment -- #2149, #2150

**Comment by maxirmx** [comment]
Regarding previously added FALLTHROUGH_STATEMENT (https://github.com/rnpgp/rnp/commit/f7ff8178c955022165f03dd36c3ff4bbadc68f15)

It was defined as 
```
# define FALLTHROUGH_STATEMENT [[fallthrough]];
```
and applied as 
```
FALLTHROUGH_STATEMENT;
```

That was not correct. The standart calls for **single** null statement, for two some compilers generate a hundred of warnings.

**Comment by ni4** [comment]
@maxirmx it got resolved (but not released yet) and it isn't our issue: https://github.com/randombit/botan/issues/3812
Actually it was a great luck to catch it!

**Comment by ni4** [comment]
@maxirmx Could you please rebase on main, as PR #2148 is merged? Or I can do that as well.

**Comment by maxirmx** [comment]
> @maxirmx Could you please rebase on main, as PR #2148 is merged? Or I can do that as well.

@ni4 I have rebased it

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Comment by ni4** [comment]
Just in case: coverage fails since one of the previous tests hit some ElGamal 'rarely-hit' code path, and now it didn't.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @maxirmx @ni4 !

**Pull request merged**
