### PR TITLE
Use FetchContent for googletest

### PR DESCRIPTION
**Pull request by thierryseegers**
This addresses issue #1542.

This replaces the use of an external CMake script that was invoked at configuration time to download googletest using `ExternalProject`. It is replaced with using `FetchContent`. The same URL and version is used. AFAICT, offline builds are still relevant so that hasn't been touched.

Some things of note:
1. The fetched content will be built with the "inherited" compilation options. That is, whatever options compilations are set globally (with `add_compile_options`, for example). 
1. I confirmed in passing that the flag `gtest_force_shared_crt` is still required. 
1. The target `gmock` target of that project would get built but fail to compile with MSVC. The version of googletest specified (@c43f710) has a line of code that is incompatible with `/std:c++latest`). Because of that, I explicitly disabled the building of the `gmock` target. It is not used anyway. On a tangential note, the fact that MSVC build has the option `/std:c++latest` set creates a discrepancy with the rest of the platforms which are built with `-std=c++11`.

### CODE REVIEW

**Comment by ni4** [comment]
@thierryseegers rebasing on master would fix cmake test failure.

**Comment by thierryseegers** [comment]
@ni4 Actually, if I'm not mistaken, the failure is just due to #1546 not being merged in yet because the failure is a check of similitude between the two `version.cmake` files and one has already been modified [here](https://github.com/rnpgp/cmake-versioning) but not yet on `master` which is what that PR will do.

**Comment by ni4** [comment]
@thierryseegers Ah, sorry, you are right. Somehow got feeling that it is already merged.

**Comment by ronaldtse** [comment]
@thierryseegers #1546 is now merged, could you help rebase? Thanks!

**Review by ronaldtse — APPROVED** [review]
Thanks for the clean up!

**Comment by ronaldtse** [comment]
Will merge once passing since this is a pure CI change.

**Comment by ronaldtse** [comment]
Merging since the #1546 merge to master is successful.

**Pull request merged**
