### PR TITLE
PGP_FINGERPRINT_HEX_SIZE should be 1+2x binary size, not 1+3x

### PR DESCRIPTION
**Pull request by andrey-utkin**

### CODE REVIEW

**Review by ni4 — APPROVED** [review]
Thanks, @andrey-utkin! Could you please rebase it on the latest master as it fixes msys/clang CI issue?

**Comment by ni4** [comment]
@andrey-utkin Thanks! We may skip codecov CI failure, as it happened due to the coverage change caused by the randomized input to some of the CLI tests.

**Comment by antonsviridenko** [comment]
Isn't this file `include/repgp/repgp_def.h` a part of public API? And therefore, by changing this definition, we change public ABI between minor release. 

I guess `3x` was intended for placing spaces between individual octets.

**Comment by andrey-utkin** [comment]
Good point about it being a part of public ABI.
Depending on the branching strategy (which is [somewhat unclear](https://github.com/rnpgp/rnp/issues/1796) ) it may or may not be OK to merge this to master any time.

I'm open to the possibility that 3x is actually what we need.

**Comment by ni4** [comment]
> Isn't this file `include/repgp/repgp_def.h` a part of public API? And therefore, by changing this definition, we change public ABI between minor releases.
> 
> I guess `3x` was intended for placing spaces between individual octets.

The only public headers are `include/rnp.h` and `include/rnp_err.h`, which expose FFI interface. All other headers are to be considerd internal, and may be changed in any way. Present naming is leftover from the (unsuccessfull) try to separate parts of the library for key/data processing, and should be refactored out at some point.

**Comment by antonsviridenko** [comment]
ok, approving and merging then

**Review by antonsviridenko — APPROVED** [review]

**Pull request merged**
