### PR TITLE
CLI: do not double-check absence of arguments.

### PR DESCRIPTION
**Pull request by ni4**
This PR:
- removes redundant NULL checks for CLI arguments which has `required_argument`.
- refactors duplicate code for settings hash/cipher algorithm.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ni4 there's one failure on MSYS at:
```
2022-02-21T13:49:09.1870071Z   3/247 Test #241: cli_tests-Misc ................................................................***Failed   78.37 sec
2022-02-21T13:49:09.1877526Z Running in C:\Users\RUNNER~1\AppData\Local\Temp\rnpctmpp7wv7ojl
2022-02-21T13:49:09.1879532Z D:/a/_temp/msys64/usr/bin/gpg.exe gpg.exe --version
2022-02-21T13:49:09.1880727Z Working directory: D:\a\_temp\msys64\home\runneradmin\local-builds\rnp-build\src\tests
2022-02-21T13:49:09.1881350Z 
2022-02-21T13:49:09.1882306Z gpg (GnuPG) 2.2.32-unknown
2022-02-21T13:49:09.1905622Z libgcrypt 1.9.4-unknown
2022-02-21T13:49:09.1906726Z Copyright (C) 2021 Free Software Foundation, Inc.
2022-02-21T13:49:09.1907413Z License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
2022-02-21T13:49:09.1908026Z This is free software: you are free to change and redistribute it.
2022-02-21T13:49:09.1908597Z There is NO WARRANTY, to the extent permitted by law.
2022-02-21T13:49:09.1908958Z 
2022-02-21T13:49:09.1909372Z Home: /home/runneradmin/.gnupg
...
```

**Comment by ni4** [comment]
@ronaldtse Yeah, and at the moment it looks like an AV in MinGW sources, still digging...

**Comment by ni4** [comment]
@ronaldtse Finally investigated and fixed issue. It was simply absence of terminating NULL in substituted utf-8 argv in MinGW builds.

**Review by antonsviridenko — APPROVED** [review]

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @ni4 @antonsviridenko !

**Pull request merged**
