### PR TITLE
Add OpenSSL backend.

### PR DESCRIPTION
**Pull request by ni4**
This PR is a preview version (not ready for production environment yet)  of the OpenSSL backend, which may be used instead of Botan. Requires at least OpenSSL v1.1.1.

Currently it runs just rnp_tests for centos 8. cli_tests support is planned for later as we cannot distinguish which backend is used by RNP right now (and which algorithms/curves are enabled).

### CODE REVIEW

**Comment by ni4** [comment]
Please do not merge yet, as v0.15.2 is still not released.

**Comment by antonsviridenko** [comment]
> as we cannot distinguish which backend is used by RNP right now (and which algorithms/curves are enabled).

but we can print this info in the CLI output, somewhere in the version or help information

**Review by antonsviridenko — APPROVED** [review]

**Comment by ni4** [comment]
> > as we cannot distinguish which backend is used by RNP right now (and which algorithms/curves are enabled).
> 
> but we can print this info in the CLI output, somewhere in the version or help information

Yeah, that would be added as a separate issue, together with a number of openssl-related ones.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
You have the honor of merging @ni4 😉

**Comment by ni4** [comment]
Thanks, @ronaldtse ! :) Just let's re-run CI to re-make sure everything is okay.

**Pull request merged**
