### PR TITLE
Release v0.17.1

### LINKED ISSUE #2189: Create v0.17.1 release with `rnp_signature_get_features`
## Description

Source: https://github.com/rnpgp/rnp/commit/74b70af135d0a1b05fe8ad63aac3f20319ebc4e8#commitcomment-138429079

From @kaie :
> Would the RNP team be willing to create a v0.17.1 release, based on the former v0.17.0 release, which adds this feature ([commit](https://github.com/rnpgp/rnp/commit/74b70af135d0a1b05fe8ad63aac3f20319ebc4e8#commitcomment-138429079))? This could allow those Linux distributions which ship RNP separately, to pick up this feature easily, and allow Thunderbird to make use of the new API in its current stable 115.x release.

### PR DESCRIPTION
**Pull request by ni4**
- Botan 3 support
- Updated OpenSSL 3 support
- Minor FFI API update, required by Thunderbird.

Fixes #2189

### CODE REVIEW

**Comment by dkg** [comment]
Is there a schedule for this release?

**Comment by ni4** [comment]
@dkg not sure about the exact date, but the only missing thing was Botan 3.3.0 support fixes, but now we have additional issue #2198. That should not take a lot of time as well.

**Comment by ronaldtse** [comment]
@ni4 the timeliness for this release is more important than codecov right now, let's get it going.

**Comment by ni4** [comment]
@maxirmx do you have any idea why macOS job fails on error related to absence of c++20 support, given that it is passed via command line? Old toolchain? Anyway,  #2211 is aimed to fix this.

**Comment by maxirmx** [comment]
> @maxirmx do you have any idea why macOS job fails on error related to absence of c++20 support, given that it is passed via command line? Old toolchain? Anyway, #2211 is aimed to fix this.

I cannot give exact answer without playing with it but  I guess it is related to the version of XCode (and SDK) in use. 
Depending on macos version GHA runner may have difefrent XCode version selected by default
For example, macos-12 runner has XCode 14.2 selected and macos-14 runner has XCode 15.0.1

We may want to use https://github.com/maxim-lobanov/setup-xcode to ensure consistency (not it uses defaults to foster flexibility)

Also c++20 support  is somewhat vague.  Looking here https://developer.apple.com/xcode/cpp/#c++20  I cannot say what version is required to ensure C++20 support

**Comment by ni4** [comment]
Okay, looks like I just wasted time trying to fix codecov/project CI check. So let's finally make a release.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @ni4 !

**Review by ribose-jeffreylau — APPROVED** [review]

**Review by maxirmx — APPROVED** [review]

**Comment by ni4** [comment]
Thanks all, let's make a release!

**Pull request merged**
