### PR TITLE
Fix coverity workflow which didn't run without RNP_TESTS variable.

### PR DESCRIPTION
**Pull request by ni4**
Currently workflow runs, but doesn't do anything due to:
```
+ ctest -j2 -R '' --output-on-failure
Test project /home/runner/work/rnp/rnp/builds/rnp-build
No tests were found!!!
```

### CODE REVIEW

**Comment by ni4** [comment]
@ronaldtse  @ribose-jeffreylau Do you have any idea how to debug this change without merging to the master first?
We really need to finally get codecov back :)

**Comment by ribose-jeffreylau** [comment]
@ni4 Maybe something like #1701?  Feel free to merge that into this branch.

**Comment by ni4** [comment]
@ribose-jeffreylau Thanks! Will check that out.

**Comment by ni4** [comment]
Argh, somehow messed up codecov and coverity (and seems it happened previously). Coverity doesn't need to run tests as it intercepts only compiler invocation, so empty RNP_TESTS is pretty correct.

**Pull request closed without merging**
