### PR TITLE
add: Basic packaging files for Debian/Ubuntu

### PR DESCRIPTION
**Pull request by BenBE**
Unless I missed some stuff this PR introduces the changes needed to build native DEB packages from the sources.

The build was tested on Ubuntu 18.04 with Botan 2.6.0 pulled in from Ubuntu 18.10 (Cosmic Cuttlefish).

Please tell me if there's anything you want me to change.

### CODE REVIEW

**Comment by dkg** [comment]
@BenBE, thanks for having done this preliminary work.  However, I hope this PR will be closed without merging.

I'm hoping to help maintain the debian packaging for RNP in Debian itself.  I put it in Debian's [NEW queue](https://ftp-master.debian.org/new/rnp_0.14.0-3.html) last week for review by the FTP team, and my packaging work can be tracked [on salsa](https://salsa.debian.org/debian/rnp/), which is mirroring the released branches of rnp development.

I have a strong preference that RNP *not* include a `debian/` directory in the upstream source.  I have made the same request to [other projects](https://github.com/libreswan/libreswan/issues/118) that were considering shipping a `debian/` directory upstream, because it makes for weird collisions with the packaging work.

If there are any concerns with the packaging work i've done (i'm sure it can always be improved, like any software work), please don't hesitate to let me know, either by a message in [the debian BTS](https://bugs.debian.org/src:rnp), or an issue here -- feel free to assign it to me if you like.

I recommend closing this PR without merging it.

**Comment by BenBE** [comment]
Reasonable. If you need any assistance with the packaging or have some questions I can initiate contact with several DDs who I know in person and work with regularly.

Feel free to close as you see fit.

**Comment by ni4** [comment]
@ronaldtse @dewyatt Any objections on closing this?

**Comment by ronaldtse** [comment]
No objections. @BenBE thank you very much for the great effort -- hope you don't mind helping out down the road! 🙇

**Pull request closed without merging**
