### PR TITLE
Use define + static_assert instead of nested MAX macro usage.

### PR DESCRIPTION
**Pull request by ni4**
...for more clean code with less defines.

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @ni4 !

**Review by w-i-n-s — APPROVED** [review]
Looks fine

**Comment by ni4** [comment]
Merging, as we have 2 approvals. Thanks!

**Comment by ronaldtse** [comment]
The commit c152f7 is now changed to 5355bd841887d5869b5cc96d7d86a9ecd1a16d3b on master after #1687 from this branch.

**Pull request merged**
