### PR TITLE
Ignore pushes to version.txt for most of the CI

### LINKED ISSUE #2226: Add version.txt to paths, ignored by tests-based CI.
## Description

...and maybe add to lint test whether it's contents are corresponding to versioning style.
Also we could add some linter which checks spelling in *.md and *.adoc files.

### PR DESCRIPTION
**Pull request by ni4**
And check version.txt contents if it is changed.
Fixes #2226

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thanks @ni4 ! Perhaps @ribose-jeffreylau can have a last look...

**Comment by ni4** [comment]
@ronaldtse Thanks! And I should also make newly added CI check work :-D Seems something went wrong with version.txt check

**Review by ribose-jeffreylau — APPROVED** [review]
Thanks @ni4!

Is it correct to say that `nix.yml` and `ubuntu.yml` are left out because we want them to run when `version.txt` changes?

**Comment by ni4** [comment]
> Thanks @ni4!
> 
> Is it correct to say that `nix.yml` and `ubuntu.yml` are left out because we want them to run when `version.txt` changes?

Ubunty was left to have at least one runner in case something may go wrong due to changes commited, nix was just overlooked :) But let's left it as well.

**Comment by ni4** [comment]
All is green + two approvals, so merging.

**Pull request merged**
