### PR TITLE
Add missing move constructor for pgp_transferable_userid_t.

### PR DESCRIPTION
**Pull request by ni4**
This is attempt to fix issues #1249 and #1244.
Since it is not reflected in our CI yet, it needs a confirmation.

### CODE REVIEW

**Comment by ni4** [comment]
It is confirmed as working in #1249 and #1244 so could be merged, I guess (once approved). Anyway we'll need to have this reflected in CI in future.

**Comment by ronaldtse** [comment]
Ping @dewyatt @antonsviridenko @rrrooommmaaa for a quick review -- this is blocking builds. Thanks!

**Comment by ronaldtse** [comment]
Ping again to @dewyatt @antonsviridenko @rrrooommmaaa

**Comment by ronaldtse** [comment]
Thanks @dewyatt !

**Pull request merged**
