### PR TITLE
Added Clang builds to Ubuntu, CentOS7, CentOS8 (+ ossl), MacOS, Debian9 and Windows-msys2 workflows

### PR DESCRIPTION
**Pull request by maxirmx**
Clang build and test for the following workflows:

- centos7
- centos8-ossl
- centos8
- debian9
- macos
- ubuntu
- windows (msys) 

Fixed:

- Build with clang-cl #1129
- clang/rnp build issue (CentOS 7 workflow) clang/rnp build issue (CentOS 7 workflow) #1670
- clang/GnuPG v2.3.0-beta983 issue (CentOS 8 workflow) clang/GnuPG v2.3.0-beta983 issue (CentOS 8 workflow) #1669
- clang/libgcrypt v1.9.3 issue (CentOS 8 workflow) clang/libgcrypt v1.9.3 issue (CentOS 8 workflow) #1668

Changes previously reviewd but not included in this PR:

- Fix to 'centos8 / pkgconfig-cmake-target' job which was disabled in the upstream version. I have a fix for it, if you need it pls. create separate issue. It may go to another PR if so.
- All convinience changes that helped to run/debug CI scripts outside GHA environment

### CODE REVIEW

**Comment by ronaldtse** [comment]
@maxirmx can you rebase this PR to remove conflicts, and clean up the history before merging (i.e. combine the multiple commits with an identical message)? Thanks.

**Comment by ronaldtse** [comment]
> Changes previously reviewd but not included in this PR:
> 
> * Fix to 'centos8 / pkgconfig-cmake-target' job which was disabled in the upstream version. I have a fix for it, if you need it pls. create separate issue. It may go to another PR if so.
> * All convinience changes that helped to run/debug CI scripts outside GHA environment

Yes let's create a separate issue for these.

* [ ] Fix `centos8/pkgconfig-cmake-target` job that is disabled in CI
* [ ] Functionality that helps run/debug CI scripts locally (outside GHA environment)

**Comment by ronaldtse** [comment]
Actually easier to squash this in order to remove the cruft.

**Comment by ronaldtse** [comment]
Just going to squash this and apply the same patches in a new PR.

**Comment by maxirmx** [comment]
> Actually easier to squash this in order to remove the cruft.

Please squash it on merge.  I specially wrote a comment for this PR that can be used for squashed commit.
I am happy to adhere to any rules but it really hurts to uncover new and new ones when I deploy a PR that takes ~300 CI job runs to polish and verify

**Comment by ronaldtse** [comment]
@maxirmx I've already cleaned up the commits and re-applied them to the new master in #1688, there should be nothing further to do for this now.

**Pull request merged**
