### PR TITLE
#1014 weird userids

### LINKED ISSUE #1014: Add tests for weird userids
## Description

Add tests which check whether library and CLI correctly works with weird uids:
 - [ ] with non-ASCII utf-8 characters
 - [ ] with special characters (\t, \n, \0x00, '|', '$', '(', etc).
 - [ ] long userid (more then MAX_ID_LENGTH)
 - [ ] zero-size userid

It should cover following use cases:
 - [ ] pass userid via CLI for key generation
 - [ ] pass userid via CLI as key recipient
 - [ ] pass userid via CLI as signer
 - [ ] list key(s)
 - [ ] dump human-readable and JSON packets
 - [ ] other usages which come to a mind

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
Here are some key generation and encryption tests for weird userids (Issue #1014)
special characters (without \0) generation and encryption
unicode generation and encryption (without icase search)
`-r` (recipient) parameter accepts regex. In order to correctly quote all imaginable characters, I changed mode to `std::regex_constants::ECMAScript`, so that special characters are escaped this way: `-r [\x7D][\x7B][\x5D][\x5B][\x29][\x5E][\x2A][\x2E][\x2B][\x28][\x09][\x0A][\x7C][\x24]@rnp`
allowing begin `^` and end `$` anchors `^[\x7D][\x7B][\x5D][\x5B][\x29][\x5E][\x2A][\x2E][\x2B][\x28][\x09][\x0A][\x7C][\x24]@rnp$`

### CODE REVIEW

**Comment by ronaldtse** [comment]
Ping @rrrooommmaaa , is this PR ready for review or is it still a draft? Thanks!

**Comment by rrrooommmaaa** [comment]
@ronaldtse I'm getting errors trying to use `WEIRD_USERID_UNICODE_2` in tests, so I'd rather debug that and then mark it as ready for review.

**Comment by ronaldtse** [comment]
Ping @rrrooommmaaa if the tests are passing we can review?

**Comment by rrrooommmaaa** [comment]
> Ping @rrrooommmaaa if the tests are passing we can review?

@ronaldtse @ni4 @dewyatt Looks like on Windows Python 3 calls `CreateProcessW` (with wide characters) as opposed to `CreateProcessA` in Python 2 where we could encode UTF-8 ourselves before the call.
Now, after the call wide characters (other than Win-1252, I suppose) are replaced with '?' and I found no way to make Windows convert it to UTF-8 automatically (`chcp 65001` didn't help),
so I implemented custom conversion to utf-8 using  `GetCommandLineW` WinAPI function (something along the lines of http://mingw.5.n7.nabble.com/does-mingw-support-wmain-instead-of-main-td10330.html
It's not perfect yet, but working.
Do you agree with the general approach?

**Comment by ni4** [comment]
@rrrooommmaaa Would you have time to get back to this and finally merge, so we have less opened and abandoned PRs?

**Comment by rrrooommmaaa** [comment]
ping @ni4 @antonsviridenko @ronaldtse @dewyatt for review

**Comment by rrrooommmaaa** [comment]
- [x] with non-ASCII utf-8 characters
 - [x] with special characters (\t, \n, \0x00, '|', '$', '(', etc).
 - [x] long userid (more then MAX_ID_LENGTH)
 - [ ] zero-size userid

It should cover following use cases:
 - [x] pass userid via CLI for key generation
 - [x] pass userid via CLI as key recipient
 - [ ] pass userid via CLI as signer
 - [x] list key(s)
 - [ ] dump human-readable and JSON packets

**Review by antonsviridenko — APPROVED** [review]

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
