### PR TITLE
Debian tests on pre-published container

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
As discussed in #1968

**Comment by maxirmx** [comment]
#1571, #1998 for Debian

**Review by ronaldtse — APPROVED** [review]

**Comment by maxirmx** [comment]
@ronaldtse 
Looking for help with https://github.com/rnpgp/rnp-ci-containers/issues/5

Thank you

**Comment by maxirmx** [comment]
Merging with one review as pure CI change

**Pull request merged**
