### PR TITLE
Allow single --edit-key subcommand only.

### LINKED ISSUE #1979: `--edit-key` sub-options should be mutually exclusive
## Description

https://github.com/rnpgp/rnp/blob/9b08ed1d13b79b3c8f2603ecc29b2cd066b70a49/src/rnp/fficli.cpp#L1091
The code above says `at least one` but
depending on the processing order, current code executes only one of the edit key subcommands.

## Steps to Reproduce

Try to pass multiple `--edit-key` subcommands/options.

## Expected Behavior

I think `rnpkeys` should print an error message on attempts to pass more than one `--edit-key` options and the error message above should be updated to address this change.

### PR DESCRIPTION
**Pull request by antonsviridenko**
Closes #1979

### CODE REVIEW

**Comment by antonsviridenko** [comment]
CLI tests will follow, ping @ni4 for preliminary review

**Comment by antonsviridenko** [comment]
maybe there is some better way to implement this...

**Comment by antonsviridenko** [comment]
ping @ni4 @ronaldtse

I don't know what's wrong with codecov/project failing test

**Review by ronaldtse — APPROVED** [review]
Thank you @antonsviridenko !

**Comment by ronaldtse** [comment]
I think the codecov issue isn’t important right now, it represents a 0.01% coverage difference.

**Comment by ni4** [comment]
@antonsviridenko In one of the previous test runs one rare codepath with ElGamal key re-generation was hit, so coverage was increased. Now (as well as in my OpenSSL PR) it didn't trigger, so codecov reports less coverage.

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
