### PR TITLE
Refactor signature checks to pgp_key_t methods.

### PR DESCRIPTION
**Pull request by ni4**
...consolidating code so we would be able to pass security context to the `pgp_key_t` and use it together with security profiles.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ni4 there's an issue discovered in the fuzzer causing that build to fail.

**Comment by ni4** [comment]
> @ni4 there's an issue discovered in the fuzzer causing that build to fail.

Yeah, it's due to exceptions thrown for unknown hash algorithm. Will update the PR once understand what's the better way to handle it.

**Comment by ni4** [comment]
@ronaldtse Now it's green and ready for review :)

**Review by antonsviridenko — APPROVED** [review]

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you very much @ni4!

**Pull request merged**
