### PR TITLE
Use container tgagor/centos:stream8 instead of EOLed centos:8

### LINKED ISSUE #1751: Upgrade "CentOS 8" build to "CentOS Stream 8" as "CentOS 8" is EOLed
Our builds are seeing:
image

https://forums.centos.org/viewtopic.php?f=54&t=78708

We have to migrate to CentOS Stream.

### PR DESCRIPTION
**Pull request by ni4**
Fixes #1751

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thanks @ni4 !

**Comment by ronaldtse** [comment]
Thanks @ni4 ! Please help merge this once the builds pass since this is a CI change that only requires a single approval.

**Comment by ni4** [comment]
@ronaldtse Ok, sure!

**Comment by ni4** [comment]
Merging, as CI passes.

**Pull request merged**
