### PR TITLE
ci: Add scheduled coverity scans

### PR DESCRIPTION
**Pull request by dewyatt**
@ronaldtse Can you add the `COVERITY_SCAN_TOKEN` secret from [here](https://scan.coverity.com/projects/riboseinc-rnp?tab=project_settings)?

### CODE REVIEW

**Comment by ronaldtse** [comment]
Had to re-add this repo to Coverity since we last moved it to the new account.

**Comment by ronaldtse** [comment]
Merging since this is only CI.

**Comment by dewyatt** [comment]
> Had to re-add this repo to Coverity since we last moved it to the new account.

Oh I forgot about that! Do you have to redo the invites, etc?

**Comment by ronaldtse** [comment]
Thanks for the reminder @dewyatt , just did the invites!

**Pull request merged**
