### PR TITLE
Fix tests which changed behaviour due to added g23 format support.

### PR DESCRIPTION
**Pull request by ni4**
Not sure why CI run successfully without these changes.

### CODE REVIEW

**Comment by maxirmx** [comment]
@ni4 
I noticed it but forgot to fix.  Sorry about it.
For those two failing these tests  ```rnp_tests_get_key_by_id(sec, id)``` returns ```false```, i.e.:  private key files are missing.
Let me fix it

**Comment by ni4** [comment]
@maxirmx Thanks for following up! I'm completely puzzled why these are running correctly locally, but completely fail in GHA.

**Comment by maxirmx** [comment]
> @maxirmx Thanks for following up! I'm completely puzzled why these are running correctly locally, but completely fail in GHA.

Possibly it was related to backend  -- https://github.com/rnpgp/rnp/issues/1960

**Comment by maxirmx** [comment]
@ni4 
I added missing key files, then made some tests conditional because of #1960, then made codecov happy with my changes
It looks like codecov has an issue  with the changes you made to src/librepgp/stream-common.cpp

**Comment by ni4** [comment]
@maxirmx looks like codecov is unhappy since this PR removes bunch of code lines which previously were covered with tests, causing lower overall coverage. So it should be good to go once tests are run succesffully.

**Review by maxirmx — APPROVED** [review]
LGTM

**Review by ronaldtse — APPROVED** [review]
Thank you @maxirmx @ni4 !

**Pull request merged**
