### PR TITLE
Fix Changelog formatting for vim

### PR DESCRIPTION
**Pull request by andreasstieger**
0.15.1 changelog contained markdown that did not format well in vim

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thank you @andreasstieger ! Merging with one approval since it is only a documentation change.

**Review by ni4 — APPROVED** [review]
LGTM, thanks!

**Comment by ni4** [comment]
@ronaldtse Looks like you forgot to push a green button :)

**Comment by ronaldtse** [comment]
I was trying to see if someone realized. Just joking I forgot... argh

**Pull request merged**
