### PR TITLE
Squash debian workflow

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
While Debian and Ubuntu are similar, the structure of GHA workflow is different for them.
Ubuntu is executed in GHA runner, Debian requires extra container. 
I do not think it is feasible to combine Ubuntu and Debian together.  This PR  combines Debian only.

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Very nice @maxirmx , thank you! (A rebase is necessary though after merging of #1969 )

**Comment by ronaldtse** [comment]
> I do not think it is feasible to combine Ubuntu and Debian together. This PR combines Debian only.

Yes that's fine. I nearly forgot GHA provides Ubuntu by default while Debian is through a Docker image.

**Comment by maxirmx** [comment]
> Very nice @maxirmx , thank you! (A rebase is necessary though after merging of #1969 )

Thank you
Rebased

**Review by ni4 — APPROVED** [review]
LGTM, thanks, @maxirmx !

**Comment by ni4** [comment]
...merging as we have two approvals.

**Pull request merged**
