### PR TITLE
Try to fix CI build cache issues

### LINKED ISSUE #1504: GHA should only use build-cache step for installing into CACHE_DIR
This causes build issues as at times this will obviously skip out things like installation of system packages, etc.

### PR DESCRIPTION
**Pull request by ribose-jeffreylau**
closes #1504

### CODE REVIEW

**Comment by ni4** [comment]
@ribose-jeffreylau JFYI: MSVC build fails randomly on too large key generation, that is unrelated to these changes.

**Comment by ni4** [comment]
@ribose-jeffreylau Looks like GTEST_SOURCES somehow lost on it's way from ENV to `main.sh`

**Review by ronaldtse — APPROVED** [review]
Thanks @ribose-jeffreylau ! Please help merge when ready!

**Comment by ronaldtse** [comment]
Thanks @ribose-jeffreylau !

**Pull request merged**
