### PR TITLE
CI: Bump used ruby version to 3.0

### LINKED ISSUE #1958: CI: Bump used ruby version to 3.0
## Description

Ruby 2.5-2.6 are already EOL (https://www.ruby-lang.org/en/downloads/branches/), and 2.7 is in security maintenance state, which should be EOL in 3 months or so.

### PR DESCRIPTION
**Pull request by ni4**
Fixes #1958

### CODE REVIEW

**Review by maxirmx — CHANGES_REQUESTED** [review]
I think that the code I have added to support Ruby 2.5 is not required anymore

This can be removed:
```
# Bundler version to use if Ruby version is less then
# FALLBACK_BUNDLER_RUBY_VERSION
: "${FALLBACK_BUNDLER_VERSION:=2.3.26}"
: "${FALLBACK_BUNDLER_RUBY_VERSION:=2.6.0}"
```
and the code that references these FALLBACK_xxx in ```install_bundler()```

**Review by antonsviridenko — APPROVED** [review]

**Comment by ronaldtse** [comment]
I have a question: I believe the Ruby version is not really relevant to this repository, but to ruby-rnp. I suggest we remove the Ruby tests from this repo and only run them in ruby-rnp, where we can test 2.7, 3.0, 3.1 and 3.2.

Any thoughts?

**Comment by maxirmx** [comment]
> I have a question: I believe the Ruby version is not really relevant to this repository, but to ruby-rnp. I suggest we remove the Ruby tests from this repo and only run them in ruby-rnp, where we can test 2.7, 3.0, 3.1 and 3.2.
> 
> Any thoughts?

I think it make a lot of sense

**Comment by ni4** [comment]
> I think that the code I have added to support Ruby 2.5 is not required anymore

@maxirmx Thanks, agree with this. Removed and force-pushed.

**Comment by ni4** [comment]
@maxirmx Please see the updated PR.

**Review by maxirmx — APPROVED** [review]
LGTM

**Comment by antonsviridenko** [comment]
@ronaldtse I agree, ruby-rnp tests frequently cause troubles, but on the other hand I thought about adding php-rnp tests here too, as we already have ruby tests in this repo 😂

**Comment by ni4** [comment]
> @ronaldtse I agree, ruby-rnp tests frequently cause troubles, but on the other hand I thought about adding php-rnp tests here too, as we already have ruby tests in this repo 😂

No, hell no :-D Actually from the architecture point of view it would be more logical to run such tests from the ruby-rnp/php-rnp repository against the latest RNP release, plus, maybe, some weekly runs to detect incompatibilities early.

**Comment by ronaldtse** [comment]
Yeah let's move away the ruby-rnp tests to ruby-rnp, and the have php-rnp tests at the php-rnp repository. GitHub Actions now provides ways for us to trigger builds so we can have a consistent setup across different language bindings. (@maxirmx can help us with that).

**Review by ronaldtse — APPROVED** [review]

**Pull request merged**
