### PR TITLE
Added --password option to rnpkeys

### LINKED ISSUE #1031: Implement --password CLI parameter for rnpkeys.
## Description

While rnp CLI has `--password` parameter, rnpkeys doesn't.
This may be useful in batch key generation when --pass-fd is not usable due to some reasons.

### LINKED ISSUE #1209: Please allow the creation of unprotected keys
## Description

We test RNP as part of the OpenPGP Interoperability Test Suite (https://tests.sequoia-pgp.org/) which includes a test to create keys.  `rnpkeys` used to be able to create keys with unprotected (sub)keys, but now it refuses to do so.  This means that we currently cannot create keys with RNP in our test suite.

(The technical reason for that is that the common interface that we use to drive the implementations that we test, the Stateless OpenPGP Command-Line Interface (https://gitlab.com/dkg/openpgp-stateless-cli) does not support protected keys, or any other operation that involves passwords.)

## Steps to Reproduce

1. `rnpkeys --generate-key --userid ...`

## Expected Behavior

Generate a key without encrypted (sub)keys.

## Actual Behavior

`rnpkeys` prompts for a password and the confirmation.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
Closes #1031
Closes #1209

### CODE REVIEW

**Comment by ni4** [comment]
@rrrooommmaaa I'd suggest to add new parameter (together with missing pass-fd) to the usage message in `rnpkeys.cpp`.
We still need to write better one/update man page but this would be usable at least now.
Also I'd add test with empty password, to make sure that it works correctly - i.e. doesn't encrypt the generated key. Then we'd be able to close #1209 as well.

**Review by antonsviridenko — APPROVED** [review]

**Comment by antonsviridenko** [comment]
> Also I'd add test with empty password, to make sure that it works correctly - i.e. doesn't encrypt the generated key.

What exactly do you mean here? No `--password` option passed or `--password ''` with empty string argument? In second case I'd expect that program encrypts generated keys using empty string as a password.

**Comment by ni4** [comment]
> What exactly do you mean here? No `--password` option passed or `--password ''` with empty string argument? In second case I'd expect that program encrypts generated keys using empty string as a password.

No `--password` option would ask the password from the terminal, I mean empty password. Actually is there any reason to encrypt key with empty password? As another option we could use separate `--no-password` parameter.

**Comment by rrrooommmaaa** [comment]
> No `--password` option would ask the password from the terminal, I mean empty password. Actually is there any reason to encrypt key with empty password? As another option we could use separate `--no-password` parameter.

I tested with `--password=` -- it correctly handles empty password and skips key protection step.

**Comment by antonsviridenko** [comment]
Ok, the spec does not say anything about empty passphrases, so I assume they could be used. But GnuPG creates unprotected key when empty passphrase is supplied, so we are consistent in this behaviour.

Btw, why do we use the term "password" instead of "passphrase"?

**Review by antonsviridenko — APPROVED** [review]

**Comment by ni4** [comment]
> Btw, why do we use the term "password" instead of "passphrase"?

Please see this for the discussion: https://github.com/rnpgp/rnp/issues/515

**Review by ni4 — APPROVED** [review]
LGTM, but please first wait for the #1366 to be merged and rebase on it, to make sure that macOS tests pass.

**Pull request merged**
