### PR TITLE
[#1872] version.txt: increment to 0.17.0

### PR DESCRIPTION
**Pull request by andrey-utkin**
This is to make it possible to differentiate between 0.16.0 and current
master. A specific case where this is needed is the CI problems with
ruby-rnp test suite in the PR backporting specific features onto 0.16.0
to make a 0.16.1: https://github.com/rnpgp/rnp/pull/1869

This should be merged at the same time with a change for ruby-rnp:
https://github.com/rnpgp/ruby-rnp/pull/81

Bug: https://github.com/rnpgp/rnp/issues/1872

### CODE REVIEW

**Review by ni4 — CHANGES_REQUESTED** [review]
This MUST NOT be merged at it goes strongly against the logic - we have v0.16.0+ sources on master and we never ever had v0.17.0 release yet.

**Comment by andrey-utkin** [comment]
Fine, but we still need to somehow tell the release from a master branch.
A couple other ways I see here. Does any of them look good to you?

1. Make the master branch have the semblance of "unstable release branch", with odd minor number, e.g. 0.17.x, then when there's time to branch from that, convert it to the even-numbered 0.18.x.

2. A special token in `version.txt` on live branches. For example, ffmpeg does it this way:
As a part of release branching procedure, right after the branching, the value of `RELEASE` file changes from `4.2.git` to `4.3.git` for master and `4.2` for the release branch.
https://git.ffmpeg.org/gitweb/ffmpeg.git/blobdiff/1ee3c984b91e0241068d1c093d222ecec2e6052c..f66f3ca2c18f00bf4fc17f7a5d346abb78be41de:/RELEASE
https://git.ffmpeg.org/gitweb/ffmpeg.git/blobdiff/0a8a96c25194b550f3b87902e1b7f061738ae3cd..c1ebaffba9fdc8948bce54b96c347ff960d1440c:/RELEASE

**Comment by ni4** [comment]
In this particular case we got problems on ruby-rnp side since planned next version was v0.17.0. Having knowledge that key expiration time commits would be included into v0.16.1, we may just fix https://github.com/rnpgp/ruby-rnp/pull/81/files with the `Rnp.version >= Rnp.version("0.16.1")` check.

**Comment by ni4** [comment]
> > In this particular case we got problems on ruby-rnp side since planned next version was v0.17.0. Having knowledge that key expiration time commits would be included into v0.16.1, we may just fix https://github.com/rnpgp/ruby-rnp/pull/81/files with the `Rnp.version >= Rnp.version("0.16.1")` check.
> 
> While this would fix it for v0.16.1 and its descendants, it won't fix it for release/0.x branch and any PRs targeting it, which ties our hands in preparing the release.

But how in practice we could need something inbetween v0.16.0 and v0.16.1?

**Comment by ronaldtse** [comment]
> > But how in practice we could need something inbetween v0.16.0 and v0.16.1?
> 
> During release preparation, for example, for PRs backporting individual features.

Agree.

**Comment by ni4** [comment]
Closing this as it was handled in a different way.

**Pull request closed without merging**
