### PR TITLE
Use AEAD-OCB by default.

### LINKED ISSUE #1918: Use AEAD OCB instead of EAX by default
> The question here is whether to add a third mode (GCM) instead of
restricting the new AEAD thing to just one mode (OCB) and dropping EAX
which is not needed anymore.

Whole email: 
https://mailarchive.ietf.org/arch/msg/openpgp/4jYV0gnSt1JV7avWlx_rY0q6VmY/

### PR DESCRIPTION
**Pull request by ni4**
Fixes #1918

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thank you @ni4 !

**Comment by ni4** [comment]
Thanks, @ronaldtse ! Codecov failure is irrelevant as related to the random case (high bits of elgamal key generation).

**Comment by antonsviridenko** [comment]
what about this one

centos9-ossl
> The following tests FAILED:
	247 - cli_tests-Compression (Failed)
Error: Process completed with exit code 8.

**Comment by ni4** [comment]
@antonsviridenko missed that. Let's restart and see whether it helps. There are some occassional password/symmetric decryption issues related to GnuPG. My guess is that those are related to concurrency/some password caching by the gpg-agent.

**Review by antonsviridenko — APPROVED** [review]

**Pull request merged**
