### PR TITLE
Fix windows compatibility issues for tests.

### PR DESCRIPTION
**Pull request by ni4**
This is a draft PR at the moment and created to make sure nothing is broken/be able later on to configure GHA for Windows.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ni4 any ETA here? Thanks!

**Comment by ni4** [comment]
@ronaldtse I'd say it's about a week, depending on amount of new compatibility surprises I'll encounter.

**Comment by ni4** [comment]
@ronaldtse @dewyatt This PR passes CI, and passes all tests locally under Windows/MSYS.
Should we review and merge it before there are GHA for Windows (so GHA will go in a separate PR)? Or do both in the same PR?

**Comment by ronaldtse** [comment]
@ni4 I think we should merge it first. Going to mark it "Ready"...

**Comment by ni4** [comment]
@ronaldtse Thanks! Then let's wait for reviews.
Maybe @kaie would be interested to check it out as well?

**Pull request merged**
