### PR TITLE
Use FFI for packet dumping

### PR DESCRIPTION
**Pull request by ni4**
This PR updates `rnp` and `redumper` code to use FFI interface for packet dumping.

### CODE REVIEW

**Comment by ni4** [comment]
Hm, it seems I hit CI issues again.
This probably should also wait for discussion finish in #900.

**Comment by ronaldtse** [comment]
Pending removal of `redumper` #900 as separate utility. Thanks @ni4 !

**Comment by ronaldtse** [comment]
And update docs please. Thanks!

**Comment by ronaldtse** [comment]
@ni4 looks like Travis failed all the "Test" tests like this:

```
make[1]: Leaving directory `/home/travis/local-builds/rnp-build'
1204make: *** [all] Error 2
1205/home/travis/.travis/functions: line 524:  7102 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
1206The command "if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then travis_wait 50 ./ci/main.sh; fi" exited with 2.
1207
```

Maybe a timeout?

**Comment by ni4** [comment]
@ronaldtse Not that cryptic, it seems I just forgot to link JSON-C to rnp:
`/usr/bin/ld: CMakeFiles/rnp.dir/fficli.cpp.o: undefined reference to symbol 'json_object_array_get_idx'`
Will check locally and update the PR.

**Comment by ni4** [comment]
Okay, now should update packet dumping test to correctly handle different time zones...

**Comment by ronaldtse** [comment]
@ni4 looking forward to have this merged 👍

**Comment by ni4** [comment]
@ronaldtse now it should be fine except AppVeyor

**Comment by ronaldtse** [comment]
Merging this despite AppVeyor unable to run; AppVeyor hasn’t been correctly setup.

**Pull request merged**
