### PR TITLE
Make hex2bin utilize rnp_hex_decode.

### PR DESCRIPTION
**Pull request by dewyatt**
The implementation of hex2bin had some bugs, mostly with handling whitespace.

### CODE REVIEW

**Comment by dewyatt** [comment]
Added tests, but it seems there's an unrelated failure in CI with Windows:
```
loading package files...
error: could not open file /var/cache/pacman/pkg/msys2-runtime-3.1.4-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: failed to commit transaction (cannot open package file)
Errors occurred, no packages were upgraded.
##[error]Process completed with exit code 1.
```

Not sure what's going on there but definitely unrelated.

**Comment by ni4** [comment]
@dewyatt Thanks for the test. Yeah, given that msys2-runtime-3.1.4-1 was released just today (adjusted to timezones), it should be something wrong with it.

**Comment by rrrooommmaaa** [comment]
@ni4 @dewyatt We have similar functions in `rnp/fficli.cpp`, like `hex_prefix_len` etc.
Can we move them to `lib/misc.cpp`?

**Comment by ni4** [comment]
@rrrooommmaaa Yeah, there is some duplication since we separated CLI from the base library code, so CLI is allowed only to use the FFI interface to interact with the library.

**Comment by ronaldtse** [comment]
Since the Windows failure is unrelated going to merge this first. Thanks!

**Pull request merged**
