### PR TITLE
Add version.txt to the repository and update CMake version module.

### LINKED ISSUE #1519: version.txt at v0.15.1 contains "0.15.0"
Looks to me like `version.txt` didn't get updated before making tag `v0.15.1`, because its contents still contains `0.15.0`.

While i could offer a specific fix for the `version.txt` file, i think the more important update needs to be made in whatever tooling is used to make an rnp release, so that `version.txt` gets automatically updated before a release.

### PR DESCRIPTION
**Pull request by ni4**
Fixes #1519

### CODE REVIEW

**Comment by ni4** [comment]
Oh, looks like I need first to update `riboseinc/cmake-versioning`...

**Review by antonsviridenko — APPROVED** [review]

**Comment by ronaldtse** [comment]
There's an issue with CMake on Windows:

```
[ 33%] Performing update step for 'googletest'
CMake Error at D:/a/_temp/msys/msys64/home/runneradmin/local-builds/rnp-build/src/tests/googletest-download/googletest-prefix/tmp/googletest-gitupdate.cmake:25 (message):

  Failed to get the hash for HEAD:

  fatal: ambiguous argument 'HEAD^commit': unknown revision or path not in
  the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'

make[2]: *** [CMakeFiles/googletest.dir/build.make:130: googletest-prefix/src/googletest-stamp/googletest-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/googletest.dir/all] Error 2
```

**Comment by ni4** [comment]
@ronaldtse Yeah, looks like something wrong with googletest itself. Also I found one error in my changes, will fix and post PR to the `cmake-versioning` repository first.

**Review by ronaldtse — APPROVED** [review]
LGTM!

**Comment by ni4** [comment]
2 approvals + CI passing = merge. Thanks all!

**Pull request merged**
