### PR TITLE
spelling cleanup (master)

### PR DESCRIPTION
**Pull request by dkg**
There are no substantive changes here, just orthographic improvements.

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
Thank you @dkg!

**Comment by ronaldtse** [comment]
Thanks @dkg for the spelling corrections. Since this is just docs I'm going to merge it.

**Comment by ronaldtse** [comment]
Actually since this involves updating error messages, waiting for one more approval.

**Comment by dkg** [comment]
Thanks for the prompt review, @ronaldtse  -- #1411 contains comparable changes for the `release/0.x` branch, if you're up for looking that one over too.

**Review by dewyatt — APPROVED** [review]
Excellent

**Comment by dewyatt** [comment]
Unrelated CI failure in cirrus, let's merge this

**Pull request merged**
