### PR TITLE
Fix man versions for the v0.15.0 release (release branch).

### PR DESCRIPTION
**Pull request by ni4**

### CODE REVIEW

**Comment by ni4** [comment]
As from https://github.com/rnpgp/rnp/pull/1475#issuecomment-816563971 :

@ronaldtse Then we'll need to update man pages again and put 0.15.1 there :) Basically, would tag re-push cause any problems?

**Comment by ronaldtse** [comment]
> Then we'll need to update man pages again and put 0.15.1 there :) Basically, would tag re-push cause any problems?

Don't think there would be problems...

I think the versions in man pages should probably be generated via CMake, not committed to the man page files.

**Comment by ronaldtse** [comment]
@ni4 b88091dc implements the CMake versioning for man pages.

**Comment by ni4** [comment]
@ronaldtse Thanks, this way it is much clear! LGTM, but cannot add me to the reviewers :)

**Review by antonsviridenko — APPROVED** [review]

**Comment by ronaldtse** [comment]
@dewyatt can you have a quick look to see if this is good to go? Thanks!

**Comment by ni4** [comment]
@dewyatt Is it good to go now, after merge to master?

**Comment by ni4** [comment]
Ping @dewyatt

**Review by dewyatt — APPROVED** [review]

**Comment by Xiretza** [comment]
> Basically, would tag re-push cause any problems?

Please don't do this again, it breaks everything downstream that expects tags to be immutable. Just create a bugfix release.

**Comment by ni4** [comment]
@Xiretza Thanks for the input. Could you please provide an example of what can be broken? Is it some cmake build process or something similar?

**Comment by Xiretza** [comment]
As an example, the AUR package (https://aur.archlinux.org/packages/rnp/) broke and had to be updated because the downloaded tarball suddenly had a different checksum. It also ruins reproducible builds because building the "old" 0.15.0 obviously produces different build products than the "new" 0.15.0, even though the version claims to be the same.

**Comment by ni4** [comment]
@Xiretza Thanks for the clarification! Will not move tags anymore.

**Pull request merged**
