### PR TITLE
Support GnuPG Extended Key Format (G23)

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
I now think this PR is worth merging otherwise it may be too big and diverse
Now it includes the following changes
- Integrated support of GnuPG extended key format
- Fixes to support ```openpgp-s2k3-ocb-aes``` private key protection for botan backend
- Additional tests for aes ciphers with AAD
- CI fixes to support breaking bundler gem release

**Comment by antonsviridenko** [comment]
> This branch has conflicts that must be resolved

**Comment by antonsviridenko** [comment]
I guess rebase on latest commit from master branch could help.

**Comment by maxirmx** [comment]
Thank you, @antonsviridenko 
I fixed some CI issues in this PR.  If they are fixed  in master prior to merge, there will be more conflicts :)

**Review by ni4 — APPROVED** [review]
LGTM, thanks, @maxirmx ! And additional thanks for CI failure fixes.

**Comment by ronaldtse** [comment]
@antonsviridenko can you give this one more look? Thanks!

**Review by antonsviridenko — APPROVED** [review]

**Pull request merged**
