### PR TITLE
Improved GHA msvc performance

### PR DESCRIPTION
**Pull request by maxirmx**
Improved GHA msvc performance

x64: from ~  1h 10m   to   ~ 30m
win32:   from ~2h 5m  to ~ 40m

Overall time shall drop to ~1h 10m   (debian9 job duration)

### CODE REVIEW

**Comment by ronaldtse** [comment]
I'm happy with this but would like someone else to review this too.

**Comment by maxirmx** [comment]
@ronaldtse, this branch is clean.  If you merge PR, it will save you 1 hour per commit

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@ni4 @antonsviridenko hoping to merge this soon, thanks!

**Review by antonsviridenko — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @maxirmx @antonsviridenko !

**Pull request merged**
